// This file is auto-generated by @hey-api/openapi-ts

import {
  http,
  type HttpHandler,
  HttpResponse,
  type HttpResponseResolver,
  type RequestHandlerOptions as RequestHandlerOptions2,
} from "msw";

import type {
  ClientOptions,
  Get1AppliancesByApplianceidPowerDistBoardResponses,
  Get1AppliancesByApplianceidSignalsResponses,
  Get1AppliancesResponses,
  Get1BleAppliancesByApplianceidPrivateMacrosResponses,
  Get1DevicesByDeviceidAppliancesResponses,
  Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses,
  Get1DevicesResponses,
  Get1EchonetliteAppliancesResponses,
  Get1HomesByHomeidDevicesResponses,
  Get1HomesByHomeidUsersResponses,
  Get1HomesResponses,
  Get1InvitesByInvitetokenResponses,
  Get1UsersMeResponses,
  Post1ApplianceOrdersData,
  Post1ApplianceOrdersResponses,
  Post1AppliancesByApplianceidAirconSettingsData,
  Post1AppliancesByApplianceidAirconSettingsResponses,
  Post1AppliancesByApplianceidData,
  Post1AppliancesByApplianceidDeleteData,
  Post1AppliancesByApplianceidDeleteResponses,
  Post1AppliancesByApplianceidFloorHeaterSettingsData,
  Post1AppliancesByApplianceidFloorHeaterSettingsResponses,
  Post1AppliancesByApplianceidLightData,
  Post1AppliancesByApplianceidLightProjectorData,
  Post1AppliancesByApplianceidLightProjectorResponses,
  Post1AppliancesByApplianceidLightResponses,
  Post1AppliancesByApplianceidPowerDistBoardChannelData,
  Post1AppliancesByApplianceidPowerDistBoardChannelResponses,
  Post1AppliancesByApplianceidResponses,
  Post1AppliancesByApplianceidSesameBotClickResponses,
  Post1AppliancesByApplianceidSignalOrdersData,
  Post1AppliancesByApplianceidSignalOrdersResponses,
  Post1AppliancesByApplianceidSignalsData,
  Post1AppliancesByApplianceidSignalsResponses,
  Post1AppliancesByApplianceidTvData,
  Post1AppliancesByApplianceidTvResponses,
  Post1AppliancesData,
  Post1AppliancesResponses,
  Post1BlePrivateMacrosByPrivatemacroidExecResponses,
  Post1DetectapplianceData,
  Post1DetectapplianceResponses,
  Post1DevicesByDeviceidData,
  Post1DevicesByDeviceidDeleteData,
  Post1DevicesByDeviceidDeleteResponses,
  Post1DevicesByDeviceidHumidityOffsetData,
  Post1DevicesByDeviceidHumidityOffsetResponses,
  Post1DevicesByDeviceidResponses,
  Post1DevicesByDeviceidTemperatureOffsetData,
  Post1DevicesByDeviceidTemperatureOffsetResponses,
  Post1EchonetliteAppliancesByApplianceidRefreshData,
  Post1EchonetliteAppliancesByApplianceidRefreshResponses,
  Post1EchonetliteAppliancesByApplianceidSetData,
  Post1EchonetliteAppliancesByApplianceidSetResponses,
  Post1EvccAppliancesByApplianceidStateData,
  Post1EvccAppliancesByApplianceidStateResponses,
  Post1HomesByHomeidData,
  Post1HomesByHomeidDeleteResponses,
  Post1HomesByHomeidInvitesResponses,
  Post1HomesByHomeidKickData,
  Post1HomesByHomeidKickResponses,
  Post1HomesByHomeidLocationDeleteData,
  Post1HomesByHomeidLocationDeleteResponses,
  Post1HomesByHomeidLocationResponses,
  Post1HomesByHomeidLocationStateUpdateResponses,
  Post1HomesByHomeidOwnerData,
  Post1HomesByHomeidOwnerResponses,
  Post1HomesByHomeidPartResponses,
  Post1HomesByHomeidResponses,
  Post1HomesByHomeidTransferByTohomeidData,
  Post1HomesByHomeidTransferByTohomeidResponses,
  Post1HomesData,
  Post1HomesResponses,
  Post1InvitesByInvitetokenResponses,
  Post1SignalsBySignalidData,
  Post1SignalsBySignalidDeleteData,
  Post1SignalsBySignalidDeleteResponses,
  Post1SignalsBySignalidResponses,
  Post1SignalsBySignalidSendData,
  Post1SignalsBySignalidSendResponses,
  Post1UsersMeData,
  Post1UsersMeResponses,
  Post2AppliancesByApplianceidAirconSettingsData,
  Post2AppliancesByApplianceidAirconSettingsResponses,
  Post2DetectapplianceData,
  Post2DetectapplianceResponses,
} from "./types.gen";

export type RequestHandlerOptions = RequestHandlerOptions2 & {
  baseUrl?: ClientOptions["baseUrl"];
  responseFallback?: "error" | "passthrough";
};

export type HandlePost1ApplianceOrdersResponse = {
  body: Post1ApplianceOrdersResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliance_orders` operation.
 */
export function handlePost1ApplianceOrders(
  response?:
    | HandlePost1ApplianceOrdersResponse
    | HttpResponseResolver<never, Post1ApplianceOrdersData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, Post1ApplianceOrdersData["body"]>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliance_orders`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1AppliancesResponse = {
  body: Get1AppliancesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/appliances` operation.
 */
export function handleGet1Appliances(
  response?: HandleGet1AppliancesResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesResponse = {
  body: Post1AppliancesResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances` operation.
 */
export function handlePost1Appliances(
  response?:
    | HandlePost1AppliancesResponse
    | HttpResponseResolver<never, Post1AppliancesData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, Post1AppliancesData["body"]>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidResponse = {
  body: Post1AppliancesByApplianceidResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}` operation.
 */
export function handlePost1AppliancesByApplianceid(
  response?:
    | HandlePost1AppliancesByApplianceidResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidAirconSettingsResponse = {
  body: Post1AppliancesByApplianceidAirconSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/aircon_settings` operation.
 */
export function handlePost1AppliancesByApplianceidAirconSettings(
  response?:
    | HandlePost1AppliancesByApplianceidAirconSettingsResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidAirconSettingsData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidAirconSettingsData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/aircon_settings`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidDeleteResponse = {
  body: Post1AppliancesByApplianceidDeleteResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/delete` operation.
 */
export function handlePost1AppliancesByApplianceidDelete(
  response?:
    | HandlePost1AppliancesByApplianceidDeleteResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidDeleteData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidDeleteData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/delete`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidFloorHeaterSettingsResponse = {
  body: Post1AppliancesByApplianceidFloorHeaterSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/floor_heater_settings` operation.
 */
export function handlePost1AppliancesByApplianceidFloorHeaterSettings(
  response?:
    | HandlePost1AppliancesByApplianceidFloorHeaterSettingsResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidFloorHeaterSettingsData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidFloorHeaterSettingsData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/floor_heater_settings`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidLightResponse = {
  body: Post1AppliancesByApplianceidLightResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/light` operation.
 */
export function handlePost1AppliancesByApplianceidLight(
  response?:
    | HandlePost1AppliancesByApplianceidLightResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidLightData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidLightData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/light`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidLightProjectorResponse = {
  body: Post1AppliancesByApplianceidLightProjectorResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/light_projector` operation.
 */
export function handlePost1AppliancesByApplianceidLightProjector(
  response?:
    | HandlePost1AppliancesByApplianceidLightProjectorResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidLightProjectorData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidLightProjectorData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/light_projector`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1AppliancesByApplianceidPowerDistBoardResponse = {
  body: Get1AppliancesByApplianceidPowerDistBoardResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/appliances/{applianceid}/power_dist_board` operation.
 */
export function handleGet1AppliancesByApplianceidPowerDistBoard(
  response?:
    | HandleGet1AppliancesByApplianceidPowerDistBoardResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      applianceid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/power_dist_board`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidPowerDistBoardChannelResponse = {
  body: Post1AppliancesByApplianceidPowerDistBoardChannelResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/power_dist_board/channel` operation.
 */
export function handlePost1AppliancesByApplianceidPowerDistBoardChannel(
  response?:
    | HandlePost1AppliancesByApplianceidPowerDistBoardChannelResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidPowerDistBoardChannelData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidPowerDistBoardChannelData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/power_dist_board/channel`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidSesameBotClickResponse = {
  body: Post1AppliancesByApplianceidSesameBotClickResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/sesame_bot/click` operation.
 */
export function handlePost1AppliancesByApplianceidSesameBotClick(
  response?:
    | HandlePost1AppliancesByApplianceidSesameBotClickResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/sesame_bot/click`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidSignalOrdersResponse = {
  body: Post1AppliancesByApplianceidSignalOrdersResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/signal_orders` operation.
 */
export function handlePost1AppliancesByApplianceidSignalOrders(
  response?:
    | HandlePost1AppliancesByApplianceidSignalOrdersResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidSignalOrdersData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidSignalOrdersData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/signal_orders`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1AppliancesByApplianceidSignalsResponse = {
  body: Get1AppliancesByApplianceidSignalsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/appliances/{applianceid}/signals` operation.
 */
export function handleGet1AppliancesByApplianceidSignals(
  response?:
    | HandleGet1AppliancesByApplianceidSignalsResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      applianceid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/signals`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidSignalsResponse = {
  body: Post1AppliancesByApplianceidSignalsResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/signals` operation.
 */
export function handlePost1AppliancesByApplianceidSignals(
  response?:
    | HandlePost1AppliancesByApplianceidSignalsResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidSignalsData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidSignalsData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/signals`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1AppliancesByApplianceidTvResponse = {
  body: Post1AppliancesByApplianceidTvResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/appliances/{applianceid}/tv` operation.
 */
export function handlePost1AppliancesByApplianceidTv(
  response?:
    | HandlePost1AppliancesByApplianceidTvResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1AppliancesByApplianceidTvData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1AppliancesByApplianceidTvData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/appliances/:applianceid/tv`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1BleAppliancesByApplianceidPrivateMacrosResponse = {
  body: Get1BleAppliancesByApplianceidPrivateMacrosResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/ble/appliances/{applianceid}/private_macros` operation.
 */
export function handleGet1BleAppliancesByApplianceidPrivateMacros(
  response?:
    | HandleGet1BleAppliancesByApplianceidPrivateMacrosResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      applianceid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/ble/appliances/:applianceid/private_macros`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1BlePrivateMacrosByPrivatemacroidExecResponse = {
  body: Post1BlePrivateMacrosByPrivatemacroidExecResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/ble/private_macros/{privatemacroid}/exec` operation.
 */
export function handlePost1BlePrivateMacrosByPrivatemacroidExec(
  response?:
    | HandlePost1BlePrivateMacrosByPrivatemacroidExecResponse
    | HttpResponseResolver<
        {
          privatemacroid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      privatemacroid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/ble/private_macros/:privatemacroid/exec`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1DetectapplianceResponse = {
  body: Post1DetectapplianceResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/detectappliance` operation.
 */
export function handlePost1Detectappliance(
  response?:
    | HandlePost1DetectapplianceResponse
    | HttpResponseResolver<never, Post1DetectapplianceData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, Post1DetectapplianceData["body"]>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/detectappliance`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1DevicesResponse = {
  body: Get1DevicesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/devices` operation.
 */
export function handleGet1Devices(
  response?: HandleGet1DevicesResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/devices`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1DevicesByDeviceidResponse = {
  body: Post1DevicesByDeviceidResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/devices/{deviceid}` operation.
 */
export function handlePost1DevicesByDeviceid(
  response?:
    | HandlePost1DevicesByDeviceidResponse
    | HttpResponseResolver<
        {
          deviceid: string;
        },
        Post1DevicesByDeviceidData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      deviceid: string;
    },
    Post1DevicesByDeviceidData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/devices/:deviceid`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1DevicesByDeviceidAppliancesResponse = {
  body: Get1DevicesByDeviceidAppliancesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/devices/{deviceid}/appliances` operation.
 */
export function handleGet1DevicesByDeviceidAppliances(
  response?:
    | HandleGet1DevicesByDeviceidAppliancesResponse
    | HttpResponseResolver<
        {
          deviceid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      deviceid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/devices/:deviceid/appliances`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1DevicesByDeviceidDeleteResponse = {
  body: Post1DevicesByDeviceidDeleteResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/devices/{deviceid}/delete` operation.
 */
export function handlePost1DevicesByDeviceidDelete(
  response?:
    | HandlePost1DevicesByDeviceidDeleteResponse
    | HttpResponseResolver<
        {
          deviceid: string;
        },
        Post1DevicesByDeviceidDeleteData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      deviceid: string;
    },
    Post1DevicesByDeviceidDeleteData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/devices/:deviceid/delete`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1DevicesByDeviceidElectricityTimeSeriesHourlyResponse = {
  body: Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/devices/{deviceid}/electricity/time_series/hourly` operation.
 */
export function handleGet1DevicesByDeviceidElectricityTimeSeriesHourly(
  response?:
    | HandleGet1DevicesByDeviceidElectricityTimeSeriesHourlyResponse
    | HttpResponseResolver<
        {
          deviceid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      deviceid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/devices/:deviceid/electricity/time_series/hourly`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1DevicesByDeviceidHumidityOffsetResponse = {
  body: Post1DevicesByDeviceidHumidityOffsetResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/devices/{deviceid}/humidity_offset` operation.
 */
export function handlePost1DevicesByDeviceidHumidityOffset(
  response?:
    | HandlePost1DevicesByDeviceidHumidityOffsetResponse
    | HttpResponseResolver<
        {
          deviceid: string;
        },
        Post1DevicesByDeviceidHumidityOffsetData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      deviceid: string;
    },
    Post1DevicesByDeviceidHumidityOffsetData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/devices/:deviceid/humidity_offset`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1DevicesByDeviceidTemperatureOffsetResponse = {
  body: Post1DevicesByDeviceidTemperatureOffsetResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/devices/{deviceid}/temperature_offset` operation.
 */
export function handlePost1DevicesByDeviceidTemperatureOffset(
  response?:
    | HandlePost1DevicesByDeviceidTemperatureOffsetResponse
    | HttpResponseResolver<
        {
          deviceid: string;
        },
        Post1DevicesByDeviceidTemperatureOffsetData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      deviceid: string;
    },
    Post1DevicesByDeviceidTemperatureOffsetData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/devices/:deviceid/temperature_offset`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1EchonetliteAppliancesResponse = {
  body: Get1EchonetliteAppliancesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/echonetlite/appliances` operation.
 */
export function handleGet1EchonetliteAppliances(
  response?: HandleGet1EchonetliteAppliancesResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/echonetlite/appliances`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1EchonetliteAppliancesByApplianceidRefreshResponse = {
  body: Post1EchonetliteAppliancesByApplianceidRefreshResponses[202];
  status?: 202;
};

/**
 * Handler for the `POST /1/echonetlite/appliances/{applianceid}/refresh` operation.
 */
export function handlePost1EchonetliteAppliancesByApplianceidRefresh(
  response?:
    | HandlePost1EchonetliteAppliancesByApplianceidRefreshResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1EchonetliteAppliancesByApplianceidRefreshData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1EchonetliteAppliancesByApplianceidRefreshData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/echonetlite/appliances/:applianceid/refresh`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 202 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1EchonetliteAppliancesByApplianceidSetResponse = {
  body: Post1EchonetliteAppliancesByApplianceidSetResponses[202];
  status?: 202;
};

/**
 * Handler for the `POST /1/echonetlite/appliances/{applianceid}/set` operation.
 */
export function handlePost1EchonetliteAppliancesByApplianceidSet(
  response?:
    | HandlePost1EchonetliteAppliancesByApplianceidSetResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1EchonetliteAppliancesByApplianceidSetData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1EchonetliteAppliancesByApplianceidSetData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/echonetlite/appliances/:applianceid/set`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 202 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1EvccAppliancesByApplianceidStateResponse = {
  body: Post1EvccAppliancesByApplianceidStateResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/evcc/appliances/{applianceid}/state` operation.
 */
export function handlePost1EvccAppliancesByApplianceidState(
  response?:
    | HandlePost1EvccAppliancesByApplianceidStateResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post1EvccAppliancesByApplianceidStateData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post1EvccAppliancesByApplianceidStateData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/evcc/appliances/:applianceid/state`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1HomesResponse = {
  body: Get1HomesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/homes` operation.
 */
export function handleGet1Homes(
  response?: HandleGet1HomesResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesResponse = {
  body: Post1HomesResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes` operation.
 */
export function handlePost1Homes(
  response?: HandlePost1HomesResponse | HttpResponseResolver<never, Post1HomesData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, Post1HomesData["body"]>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidResponse = {
  body: Post1HomesByHomeidResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}` operation.
 */
export function handlePost1HomesByHomeid(
  response?:
    | HandlePost1HomesByHomeidResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        Post1HomesByHomeidData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    Post1HomesByHomeidData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidDeleteResponse = {
  body: Post1HomesByHomeidDeleteResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/delete` operation.
 */
export function handlePost1HomesByHomeidDelete(
  response?:
    | HandlePost1HomesByHomeidDeleteResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/delete`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1HomesByHomeidDevicesResponse = {
  body: Get1HomesByHomeidDevicesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/homes/{homeid}/devices` operation.
 */
export function handleGet1HomesByHomeidDevices(
  response?:
    | HandleGet1HomesByHomeidDevicesResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      homeid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/devices`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidInvitesResponse = {
  body: Post1HomesByHomeidInvitesResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/invites` operation.
 */
export function handlePost1HomesByHomeidInvites(
  response?:
    | HandlePost1HomesByHomeidInvitesResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/invites`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidKickResponse = {
  body: Post1HomesByHomeidKickResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/kick` operation.
 */
export function handlePost1HomesByHomeidKick(
  response?:
    | HandlePost1HomesByHomeidKickResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        Post1HomesByHomeidKickData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    Post1HomesByHomeidKickData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/kick`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidLocationResponse = {
  body: Post1HomesByHomeidLocationResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/location` operation.
 */
export function handlePost1HomesByHomeidLocation(
  response?:
    | HandlePost1HomesByHomeidLocationResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/location`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidLocationDeleteResponse = {
  body: Post1HomesByHomeidLocationDeleteResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/location/delete` operation.
 */
export function handlePost1HomesByHomeidLocationDelete(
  response?:
    | HandlePost1HomesByHomeidLocationDeleteResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        Post1HomesByHomeidLocationDeleteData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    Post1HomesByHomeidLocationDeleteData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/location/delete`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidLocationStateUpdateResponse = {
  body: Post1HomesByHomeidLocationStateUpdateResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/location_state/update` operation.
 */
export function handlePost1HomesByHomeidLocationStateUpdate(
  response?:
    | HandlePost1HomesByHomeidLocationStateUpdateResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/location_state/update`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidOwnerResponse = {
  body: Post1HomesByHomeidOwnerResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/owner` operation.
 */
export function handlePost1HomesByHomeidOwner(
  response?:
    | HandlePost1HomesByHomeidOwnerResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        Post1HomesByHomeidOwnerData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    Post1HomesByHomeidOwnerData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/owner`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidPartResponse = {
  body: Post1HomesByHomeidPartResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/part` operation.
 */
export function handlePost1HomesByHomeidPart(
  response?:
    | HandlePost1HomesByHomeidPartResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/part`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1HomesByHomeidTransferByTohomeidResponse = {
  body: Post1HomesByHomeidTransferByTohomeidResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/homes/{homeid}/transfer/{tohomeid}` operation.
 */
export function handlePost1HomesByHomeidTransferByTohomeid(
  response?:
    | HandlePost1HomesByHomeidTransferByTohomeidResponse
    | HttpResponseResolver<
        {
          homeid: string;
          tohomeid: string;
        },
        Post1HomesByHomeidTransferByTohomeidData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      homeid: string;
      tohomeid: string;
    },
    Post1HomesByHomeidTransferByTohomeidData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/transfer/:tohomeid`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1HomesByHomeidUsersResponse = {
  body: Get1HomesByHomeidUsersResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/homes/{homeid}/users` operation.
 */
export function handleGet1HomesByHomeidUsers(
  response?:
    | HandleGet1HomesByHomeidUsersResponse
    | HttpResponseResolver<
        {
          homeid: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      homeid: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/homes/:homeid/users`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1InvitesByInvitetokenResponse = {
  body: Get1InvitesByInvitetokenResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/invites/{invitetoken}` operation.
 */
export function handleGet1InvitesByInvitetoken(
  response?:
    | HandleGet1InvitesByInvitetokenResponse
    | HttpResponseResolver<
        {
          invitetoken: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<
    {
      invitetoken: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/invites/:invitetoken`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1InvitesByInvitetokenResponse = {
  body: Post1InvitesByInvitetokenResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/invites/{invitetoken}` operation.
 */
export function handlePost1InvitesByInvitetoken(
  response?:
    | HandlePost1InvitesByInvitetokenResponse
    | HttpResponseResolver<
        {
          invitetoken: string;
        },
        never
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      invitetoken: string;
    },
    never
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/invites/:invitetoken`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1SignalsBySignalidResponse = {
  body: Post1SignalsBySignalidResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/signals/{signalid}` operation.
 */
export function handlePost1SignalsBySignalid(
  response?:
    | HandlePost1SignalsBySignalidResponse
    | HttpResponseResolver<
        {
          signalid: string;
        },
        Post1SignalsBySignalidData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      signalid: string;
    },
    Post1SignalsBySignalidData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/signals/:signalid`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1SignalsBySignalidDeleteResponse = {
  body: Post1SignalsBySignalidDeleteResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/signals/{signalid}/delete` operation.
 */
export function handlePost1SignalsBySignalidDelete(
  response?:
    | HandlePost1SignalsBySignalidDeleteResponse
    | HttpResponseResolver<
        {
          signalid: string;
        },
        Post1SignalsBySignalidDeleteData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      signalid: string;
    },
    Post1SignalsBySignalidDeleteData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/signals/:signalid/delete`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1SignalsBySignalidSendResponse = {
  body: Post1SignalsBySignalidSendResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/signals/{signalid}/send` operation.
 */
export function handlePost1SignalsBySignalidSend(
  response?:
    | HandlePost1SignalsBySignalidSendResponse
    | HttpResponseResolver<
        {
          signalid: string;
        },
        Post1SignalsBySignalidSendData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      signalid: string;
    },
    Post1SignalsBySignalidSendData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/signals/:signalid/send`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandleGet1UsersMeResponse = {
  body: Get1UsersMeResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /1/users/me` operation.
 */
export function handleGet1UsersMe(
  response?: HandleGet1UsersMeResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/users/me`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost1UsersMeResponse = {
  body: Post1UsersMeResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /1/users/me` operation.
 */
export function handlePost1UsersMe(
  response?: HandlePost1UsersMeResponse | HttpResponseResolver<never, Post1UsersMeData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, Post1UsersMeData["body"]>(
    `${options?.baseUrl ?? "https://api.nature.global"}/1/users/me`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost2AppliancesByApplianceidAirconSettingsResponse = {
  body: Post2AppliancesByApplianceidAirconSettingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /2/appliances/{applianceid}/aircon_settings` operation.
 */
export function handlePost2AppliancesByApplianceidAirconSettings(
  response?:
    | HandlePost2AppliancesByApplianceidAirconSettingsResponse
    | HttpResponseResolver<
        {
          applianceid: string;
        },
        Post2AppliancesByApplianceidAirconSettingsData["body"]
      >,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<
    {
      applianceid: string;
    },
    Post2AppliancesByApplianceidAirconSettingsData["body"]
  >(
    `${options?.baseUrl ?? "https://api.nature.global"}/2/appliances/:applianceid/aircon_settings`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type HandlePost2DetectapplianceResponse = {
  body: Post2DetectapplianceResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /2/detectappliance` operation.
 */
export function handlePost2Detectappliance(
  response?:
    | HandlePost2DetectapplianceResponse
    | HttpResponseResolver<never, Post2DetectapplianceData["body"]>,
  options?: RequestHandlerOptions,
): HttpHandler {
  return http.post<never, Post2DetectapplianceData["body"]>(
    `${options?.baseUrl ?? "https://api.nature.global"}/2/detectappliance`,
    (info) => {
      if (typeof response === "function") {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === "passthrough") {
        return;
      }
      return new Response("Not Implemented", {
        status: 501,
        statusText: "Not Implemented",
      });
    },
    options,
  );
}

export type MswHandlerFactories = {
  /**
   * Handler for the `POST /1/appliance_orders` operation.
   */
  post1ApplianceOrders: typeof handlePost1ApplianceOrders;
  /**
   * Handler for the `GET /1/appliances` operation.
   */
  get1Appliances: typeof handleGet1Appliances;
  /**
   * Handler for the `POST /1/appliances` operation.
   */
  post1Appliances: typeof handlePost1Appliances;
  /**
   * Handler for the `POST /1/appliances/{applianceid}` operation.
   */
  post1AppliancesByApplianceid: typeof handlePost1AppliancesByApplianceid;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/aircon_settings` operation.
   */
  post1AppliancesByApplianceidAirconSettings: typeof handlePost1AppliancesByApplianceidAirconSettings;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/delete` operation.
   */
  post1AppliancesByApplianceidDelete: typeof handlePost1AppliancesByApplianceidDelete;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/floor_heater_settings` operation.
   */
  post1AppliancesByApplianceidFloorHeaterSettings: typeof handlePost1AppliancesByApplianceidFloorHeaterSettings;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/light` operation.
   */
  post1AppliancesByApplianceidLight: typeof handlePost1AppliancesByApplianceidLight;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/light_projector` operation.
   */
  post1AppliancesByApplianceidLightProjector: typeof handlePost1AppliancesByApplianceidLightProjector;
  /**
   * Handler for the `GET /1/appliances/{applianceid}/power_dist_board` operation.
   */
  get1AppliancesByApplianceidPowerDistBoard: typeof handleGet1AppliancesByApplianceidPowerDistBoard;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/power_dist_board/channel` operation.
   */
  post1AppliancesByApplianceidPowerDistBoardChannel: typeof handlePost1AppliancesByApplianceidPowerDistBoardChannel;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/sesame_bot/click` operation.
   */
  post1AppliancesByApplianceidSesameBotClick: typeof handlePost1AppliancesByApplianceidSesameBotClick;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/signal_orders` operation.
   */
  post1AppliancesByApplianceidSignalOrders: typeof handlePost1AppliancesByApplianceidSignalOrders;
  /**
   * Handler for the `GET /1/appliances/{applianceid}/signals` operation.
   */
  get1AppliancesByApplianceidSignals: typeof handleGet1AppliancesByApplianceidSignals;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/signals` operation.
   */
  post1AppliancesByApplianceidSignals: typeof handlePost1AppliancesByApplianceidSignals;
  /**
   * Handler for the `POST /1/appliances/{applianceid}/tv` operation.
   */
  post1AppliancesByApplianceidTv: typeof handlePost1AppliancesByApplianceidTv;
  /**
   * Handler for the `GET /1/ble/appliances/{applianceid}/private_macros` operation.
   */
  get1BleAppliancesByApplianceidPrivateMacros: typeof handleGet1BleAppliancesByApplianceidPrivateMacros;
  /**
   * Handler for the `POST /1/ble/private_macros/{privatemacroid}/exec` operation.
   */
  post1BlePrivateMacrosByPrivatemacroidExec: typeof handlePost1BlePrivateMacrosByPrivatemacroidExec;
  /**
   * Handler for the `POST /1/detectappliance` operation.
   */
  post1Detectappliance: typeof handlePost1Detectappliance;
  /**
   * Handler for the `GET /1/devices` operation.
   */
  get1Devices: typeof handleGet1Devices;
  /**
   * Handler for the `POST /1/devices/{deviceid}` operation.
   */
  post1DevicesByDeviceid: typeof handlePost1DevicesByDeviceid;
  /**
   * Handler for the `GET /1/devices/{deviceid}/appliances` operation.
   */
  get1DevicesByDeviceidAppliances: typeof handleGet1DevicesByDeviceidAppliances;
  /**
   * Handler for the `POST /1/devices/{deviceid}/delete` operation.
   */
  post1DevicesByDeviceidDelete: typeof handlePost1DevicesByDeviceidDelete;
  /**
   * Handler for the `GET /1/devices/{deviceid}/electricity/time_series/hourly` operation.
   */
  get1DevicesByDeviceidElectricityTimeSeriesHourly: typeof handleGet1DevicesByDeviceidElectricityTimeSeriesHourly;
  /**
   * Handler for the `POST /1/devices/{deviceid}/humidity_offset` operation.
   */
  post1DevicesByDeviceidHumidityOffset: typeof handlePost1DevicesByDeviceidHumidityOffset;
  /**
   * Handler for the `POST /1/devices/{deviceid}/temperature_offset` operation.
   */
  post1DevicesByDeviceidTemperatureOffset: typeof handlePost1DevicesByDeviceidTemperatureOffset;
  /**
   * Handler for the `GET /1/echonetlite/appliances` operation.
   */
  get1EchonetliteAppliances: typeof handleGet1EchonetliteAppliances;
  /**
   * Handler for the `POST /1/echonetlite/appliances/{applianceid}/refresh` operation.
   */
  post1EchonetliteAppliancesByApplianceidRefresh: typeof handlePost1EchonetliteAppliancesByApplianceidRefresh;
  /**
   * Handler for the `POST /1/echonetlite/appliances/{applianceid}/set` operation.
   */
  post1EchonetliteAppliancesByApplianceidSet: typeof handlePost1EchonetliteAppliancesByApplianceidSet;
  /**
   * Handler for the `POST /1/evcc/appliances/{applianceid}/state` operation.
   */
  post1EvccAppliancesByApplianceidState: typeof handlePost1EvccAppliancesByApplianceidState;
  /**
   * Handler for the `GET /1/homes` operation.
   */
  get1Homes: typeof handleGet1Homes;
  /**
   * Handler for the `POST /1/homes` operation.
   */
  post1Homes: typeof handlePost1Homes;
  /**
   * Handler for the `POST /1/homes/{homeid}` operation.
   */
  post1HomesByHomeid: typeof handlePost1HomesByHomeid;
  /**
   * Handler for the `POST /1/homes/{homeid}/delete` operation.
   */
  post1HomesByHomeidDelete: typeof handlePost1HomesByHomeidDelete;
  /**
   * Handler for the `GET /1/homes/{homeid}/devices` operation.
   */
  get1HomesByHomeidDevices: typeof handleGet1HomesByHomeidDevices;
  /**
   * Handler for the `POST /1/homes/{homeid}/invites` operation.
   */
  post1HomesByHomeidInvites: typeof handlePost1HomesByHomeidInvites;
  /**
   * Handler for the `POST /1/homes/{homeid}/kick` operation.
   */
  post1HomesByHomeidKick: typeof handlePost1HomesByHomeidKick;
  /**
   * Handler for the `POST /1/homes/{homeid}/location` operation.
   */
  post1HomesByHomeidLocation: typeof handlePost1HomesByHomeidLocation;
  /**
   * Handler for the `POST /1/homes/{homeid}/location/delete` operation.
   */
  post1HomesByHomeidLocationDelete: typeof handlePost1HomesByHomeidLocationDelete;
  /**
   * Handler for the `POST /1/homes/{homeid}/location_state/update` operation.
   */
  post1HomesByHomeidLocationStateUpdate: typeof handlePost1HomesByHomeidLocationStateUpdate;
  /**
   * Handler for the `POST /1/homes/{homeid}/owner` operation.
   */
  post1HomesByHomeidOwner: typeof handlePost1HomesByHomeidOwner;
  /**
   * Handler for the `POST /1/homes/{homeid}/part` operation.
   */
  post1HomesByHomeidPart: typeof handlePost1HomesByHomeidPart;
  /**
   * Handler for the `POST /1/homes/{homeid}/transfer/{tohomeid}` operation.
   */
  post1HomesByHomeidTransferByTohomeid: typeof handlePost1HomesByHomeidTransferByTohomeid;
  /**
   * Handler for the `GET /1/homes/{homeid}/users` operation.
   */
  get1HomesByHomeidUsers: typeof handleGet1HomesByHomeidUsers;
  /**
   * Handler for the `GET /1/invites/{invitetoken}` operation.
   */
  get1InvitesByInvitetoken: typeof handleGet1InvitesByInvitetoken;
  /**
   * Handler for the `POST /1/invites/{invitetoken}` operation.
   */
  post1InvitesByInvitetoken: typeof handlePost1InvitesByInvitetoken;
  /**
   * Handler for the `POST /1/signals/{signalid}` operation.
   */
  post1SignalsBySignalid: typeof handlePost1SignalsBySignalid;
  /**
   * Handler for the `POST /1/signals/{signalid}/delete` operation.
   */
  post1SignalsBySignalidDelete: typeof handlePost1SignalsBySignalidDelete;
  /**
   * Handler for the `POST /1/signals/{signalid}/send` operation.
   */
  post1SignalsBySignalidSend: typeof handlePost1SignalsBySignalidSend;
  /**
   * Handler for the `GET /1/users/me` operation.
   */
  get1UsersMe: typeof handleGet1UsersMe;
  /**
   * Handler for the `POST /1/users/me` operation.
   */
  post1UsersMe: typeof handlePost1UsersMe;
  /**
   * Handler for the `POST /2/appliances/{applianceid}/aircon_settings` operation.
   */
  post2AppliancesByApplianceidAirconSettings: typeof handlePost2AppliancesByApplianceidAirconSettings;
  /**
   * Handler for the `POST /2/detectappliance` operation.
   */
  post2Detectappliance: typeof handlePost2Detectappliance;
};

export type CreateMswHandlersResult = {
  all: (options?: {
    pick?: {
      [K in keyof MswHandlerFactories]?:
        | Parameters<MswHandlerFactories[K]>[0]
        | Parameters<MswHandlerFactories[K]>;
    };
  }) => ReadonlyArray<HttpHandler>;
  pick: MswHandlerFactories;
};

export function createMswHandlers(config: RequestHandlerOptions = {}): CreateMswHandlersResult {
  type Handler<R> = (response?: R, options?: RequestHandlerOptions) => HttpHandler;
  function wrap<R>(handler: Handler<R>): Handler<R> {
    return (response, options) => handler(response, { ...config, ...options });
  }
  const pick: CreateMswHandlersResult["pick"] = {
    post1ApplianceOrders: wrap(handlePost1ApplianceOrders),
    get1Appliances: wrap(handleGet1Appliances),
    post1Appliances: wrap(handlePost1Appliances),
    post1AppliancesByApplianceid: wrap(handlePost1AppliancesByApplianceid),
    post1AppliancesByApplianceidAirconSettings: wrap(
      handlePost1AppliancesByApplianceidAirconSettings,
    ),
    post1AppliancesByApplianceidDelete: wrap(handlePost1AppliancesByApplianceidDelete),
    post1AppliancesByApplianceidFloorHeaterSettings: wrap(
      handlePost1AppliancesByApplianceidFloorHeaterSettings,
    ),
    post1AppliancesByApplianceidLight: wrap(handlePost1AppliancesByApplianceidLight),
    post1AppliancesByApplianceidLightProjector: wrap(
      handlePost1AppliancesByApplianceidLightProjector,
    ),
    get1AppliancesByApplianceidPowerDistBoard: wrap(
      handleGet1AppliancesByApplianceidPowerDistBoard,
    ),
    post1AppliancesByApplianceidPowerDistBoardChannel: wrap(
      handlePost1AppliancesByApplianceidPowerDistBoardChannel,
    ),
    post1AppliancesByApplianceidSesameBotClick: wrap(
      handlePost1AppliancesByApplianceidSesameBotClick,
    ),
    post1AppliancesByApplianceidSignalOrders: wrap(handlePost1AppliancesByApplianceidSignalOrders),
    get1AppliancesByApplianceidSignals: wrap(handleGet1AppliancesByApplianceidSignals),
    post1AppliancesByApplianceidSignals: wrap(handlePost1AppliancesByApplianceidSignals),
    post1AppliancesByApplianceidTv: wrap(handlePost1AppliancesByApplianceidTv),
    get1BleAppliancesByApplianceidPrivateMacros: wrap(
      handleGet1BleAppliancesByApplianceidPrivateMacros,
    ),
    post1BlePrivateMacrosByPrivatemacroidExec: wrap(
      handlePost1BlePrivateMacrosByPrivatemacroidExec,
    ),
    post1Detectappliance: wrap(handlePost1Detectappliance),
    get1Devices: wrap(handleGet1Devices),
    post1DevicesByDeviceid: wrap(handlePost1DevicesByDeviceid),
    get1DevicesByDeviceidAppliances: wrap(handleGet1DevicesByDeviceidAppliances),
    post1DevicesByDeviceidDelete: wrap(handlePost1DevicesByDeviceidDelete),
    get1DevicesByDeviceidElectricityTimeSeriesHourly: wrap(
      handleGet1DevicesByDeviceidElectricityTimeSeriesHourly,
    ),
    post1DevicesByDeviceidHumidityOffset: wrap(handlePost1DevicesByDeviceidHumidityOffset),
    post1DevicesByDeviceidTemperatureOffset: wrap(handlePost1DevicesByDeviceidTemperatureOffset),
    get1EchonetliteAppliances: wrap(handleGet1EchonetliteAppliances),
    post1EchonetliteAppliancesByApplianceidRefresh: wrap(
      handlePost1EchonetliteAppliancesByApplianceidRefresh,
    ),
    post1EchonetliteAppliancesByApplianceidSet: wrap(
      handlePost1EchonetliteAppliancesByApplianceidSet,
    ),
    post1EvccAppliancesByApplianceidState: wrap(handlePost1EvccAppliancesByApplianceidState),
    get1Homes: wrap(handleGet1Homes),
    post1Homes: wrap(handlePost1Homes),
    post1HomesByHomeid: wrap(handlePost1HomesByHomeid),
    post1HomesByHomeidDelete: wrap(handlePost1HomesByHomeidDelete),
    get1HomesByHomeidDevices: wrap(handleGet1HomesByHomeidDevices),
    post1HomesByHomeidInvites: wrap(handlePost1HomesByHomeidInvites),
    post1HomesByHomeidKick: wrap(handlePost1HomesByHomeidKick),
    post1HomesByHomeidLocation: wrap(handlePost1HomesByHomeidLocation),
    post1HomesByHomeidLocationDelete: wrap(handlePost1HomesByHomeidLocationDelete),
    post1HomesByHomeidLocationStateUpdate: wrap(handlePost1HomesByHomeidLocationStateUpdate),
    post1HomesByHomeidOwner: wrap(handlePost1HomesByHomeidOwner),
    post1HomesByHomeidPart: wrap(handlePost1HomesByHomeidPart),
    post1HomesByHomeidTransferByTohomeid: wrap(handlePost1HomesByHomeidTransferByTohomeid),
    get1HomesByHomeidUsers: wrap(handleGet1HomesByHomeidUsers),
    get1InvitesByInvitetoken: wrap(handleGet1InvitesByInvitetoken),
    post1InvitesByInvitetoken: wrap(handlePost1InvitesByInvitetoken),
    post1SignalsBySignalid: wrap(handlePost1SignalsBySignalid),
    post1SignalsBySignalidDelete: wrap(handlePost1SignalsBySignalidDelete),
    post1SignalsBySignalidSend: wrap(handlePost1SignalsBySignalidSend),
    get1UsersMe: wrap(handleGet1UsersMe),
    post1UsersMe: wrap(handlePost1UsersMe),
    post2AppliancesByApplianceidAirconSettings: wrap(
      handlePost2AppliancesByApplianceidAirconSettings,
    ),
    post2Detectappliance: wrap(handlePost2Detectappliance),
  };
  const all: CreateMswHandlersResult["all"] = (options = {}) => {
    type OverrideValue<R> = R | [response?: R, options?: RequestHandlerOptions];
    function invoke<R>(fn: Handler<R>, override?: OverrideValue<R>): HttpHandler {
      return Array.isArray(override) ? fn(...override) : fn(override);
    }
    const overrides = options.pick ?? {};
    return [
      invoke(
        pick.get1DevicesByDeviceidElectricityTimeSeriesHourly,
        overrides.get1DevicesByDeviceidElectricityTimeSeriesHourly,
      ),
      invoke(
        pick.get1BleAppliancesByApplianceidPrivateMacros,
        overrides.get1BleAppliancesByApplianceidPrivateMacros,
      ),
      invoke(
        pick.post1BlePrivateMacrosByPrivatemacroidExec,
        overrides.post1BlePrivateMacrosByPrivatemacroidExec,
      ),
      invoke(
        pick.post1EchonetliteAppliancesByApplianceidRefresh,
        overrides.post1EchonetliteAppliancesByApplianceidRefresh,
      ),
      invoke(
        pick.post1EchonetliteAppliancesByApplianceidSet,
        overrides.post1EchonetliteAppliancesByApplianceidSet,
      ),
      invoke(
        pick.post1EvccAppliancesByApplianceidState,
        overrides.post1EvccAppliancesByApplianceidState,
      ),
      invoke(
        pick.post1AppliancesByApplianceidPowerDistBoardChannel,
        overrides.post1AppliancesByApplianceidPowerDistBoardChannel,
      ),
      invoke(
        pick.post1AppliancesByApplianceidSesameBotClick,
        overrides.post1AppliancesByApplianceidSesameBotClick,
      ),
      invoke(pick.post1HomesByHomeidLocationDelete, overrides.post1HomesByHomeidLocationDelete),
      invoke(
        pick.post1HomesByHomeidLocationStateUpdate,
        overrides.post1HomesByHomeidLocationStateUpdate,
      ),
      invoke(
        pick.post1HomesByHomeidTransferByTohomeid,
        overrides.post1HomesByHomeidTransferByTohomeid,
      ),
      invoke(
        pick.post1AppliancesByApplianceidAirconSettings,
        overrides.post1AppliancesByApplianceidAirconSettings,
      ),
      invoke(pick.post1AppliancesByApplianceidDelete, overrides.post1AppliancesByApplianceidDelete),
      invoke(
        pick.post1AppliancesByApplianceidFloorHeaterSettings,
        overrides.post1AppliancesByApplianceidFloorHeaterSettings,
      ),
      invoke(pick.post1AppliancesByApplianceidLight, overrides.post1AppliancesByApplianceidLight),
      invoke(
        pick.post1AppliancesByApplianceidLightProjector,
        overrides.post1AppliancesByApplianceidLightProjector,
      ),
      invoke(
        pick.get1AppliancesByApplianceidPowerDistBoard,
        overrides.get1AppliancesByApplianceidPowerDistBoard,
      ),
      invoke(
        pick.post1AppliancesByApplianceidSignalOrders,
        overrides.post1AppliancesByApplianceidSignalOrders,
      ),
      invoke(pick.get1AppliancesByApplianceidSignals, overrides.get1AppliancesByApplianceidSignals),
      invoke(
        pick.post1AppliancesByApplianceidSignals,
        overrides.post1AppliancesByApplianceidSignals,
      ),
      invoke(pick.post1AppliancesByApplianceidTv, overrides.post1AppliancesByApplianceidTv),
      invoke(pick.get1DevicesByDeviceidAppliances, overrides.get1DevicesByDeviceidAppliances),
      invoke(pick.post1DevicesByDeviceidDelete, overrides.post1DevicesByDeviceidDelete),
      invoke(
        pick.post1DevicesByDeviceidHumidityOffset,
        overrides.post1DevicesByDeviceidHumidityOffset,
      ),
      invoke(
        pick.post1DevicesByDeviceidTemperatureOffset,
        overrides.post1DevicesByDeviceidTemperatureOffset,
      ),
      invoke(pick.post1HomesByHomeidDelete, overrides.post1HomesByHomeidDelete),
      invoke(pick.get1HomesByHomeidDevices, overrides.get1HomesByHomeidDevices),
      invoke(pick.post1HomesByHomeidInvites, overrides.post1HomesByHomeidInvites),
      invoke(pick.post1HomesByHomeidKick, overrides.post1HomesByHomeidKick),
      invoke(pick.post1HomesByHomeidLocation, overrides.post1HomesByHomeidLocation),
      invoke(pick.post1HomesByHomeidOwner, overrides.post1HomesByHomeidOwner),
      invoke(pick.post1HomesByHomeidPart, overrides.post1HomesByHomeidPart),
      invoke(pick.get1HomesByHomeidUsers, overrides.get1HomesByHomeidUsers),
      invoke(pick.post1SignalsBySignalidDelete, overrides.post1SignalsBySignalidDelete),
      invoke(pick.post1SignalsBySignalidSend, overrides.post1SignalsBySignalidSend),
      invoke(
        pick.post2AppliancesByApplianceidAirconSettings,
        overrides.post2AppliancesByApplianceidAirconSettings,
      ),
      invoke(pick.get1EchonetliteAppliances, overrides.get1EchonetliteAppliances),
      invoke(pick.get1UsersMe, overrides.get1UsersMe),
      invoke(pick.post1UsersMe, overrides.post1UsersMe),
      invoke(pick.post1AppliancesByApplianceid, overrides.post1AppliancesByApplianceid),
      invoke(pick.post1DevicesByDeviceid, overrides.post1DevicesByDeviceid),
      invoke(pick.post1HomesByHomeid, overrides.post1HomesByHomeid),
      invoke(pick.get1InvitesByInvitetoken, overrides.get1InvitesByInvitetoken),
      invoke(pick.post1InvitesByInvitetoken, overrides.post1InvitesByInvitetoken),
      invoke(pick.post1SignalsBySignalid, overrides.post1SignalsBySignalid),
      invoke(pick.post1ApplianceOrders, overrides.post1ApplianceOrders),
      invoke(pick.get1Appliances, overrides.get1Appliances),
      invoke(pick.post1Appliances, overrides.post1Appliances),
      invoke(pick.post1Detectappliance, overrides.post1Detectappliance),
      invoke(pick.get1Devices, overrides.get1Devices),
      invoke(pick.get1Homes, overrides.get1Homes),
      invoke(pick.post1Homes, overrides.post1Homes),
      invoke(pick.post2Detectappliance, overrides.post2Detectappliance),
    ];
  };
  return { all, pick };
}
