// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

import {
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client";
import { client } from "./client.gen";
import type {
  Get1AppliancesByApplianceidPowerDistBoardData,
  Get1AppliancesByApplianceidPowerDistBoardResponses,
  Get1AppliancesByApplianceidSignalsData,
  Get1AppliancesByApplianceidSignalsResponses,
  Get1AppliancesData,
  Get1AppliancesResponses,
  Get1BleAppliancesByApplianceidPrivateMacrosData,
  Get1BleAppliancesByApplianceidPrivateMacrosResponses,
  Get1DevicesByDeviceidAppliancesData,
  Get1DevicesByDeviceidAppliancesResponses,
  Get1DevicesByDeviceidElectricityTimeSeriesHourlyData,
  Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses,
  Get1DevicesData,
  Get1DevicesResponses,
  Get1EchonetliteAppliancesData,
  Get1EchonetliteAppliancesResponses,
  Get1HomesByHomeidDevicesData,
  Get1HomesByHomeidDevicesResponses,
  Get1HomesByHomeidUsersData,
  Get1HomesByHomeidUsersResponses,
  Get1HomesData,
  Get1HomesResponses,
  Get1InvitesByInvitetokenData,
  Get1InvitesByInvitetokenResponses,
  Get1UsersMeData,
  Get1UsersMeResponses,
  Post1ApplianceOrdersData,
  Post1ApplianceOrdersResponses,
  Post1AppliancesByApplianceidAirconSettingsData,
  Post1AppliancesByApplianceidAirconSettingsResponses,
  Post1AppliancesByApplianceidData,
  Post1AppliancesByApplianceidDeleteData,
  Post1AppliancesByApplianceidDeleteResponses,
  Post1AppliancesByApplianceidFloorHeaterSettingsData,
  Post1AppliancesByApplianceidFloorHeaterSettingsResponses,
  Post1AppliancesByApplianceidLightData,
  Post1AppliancesByApplianceidLightProjectorData,
  Post1AppliancesByApplianceidLightProjectorResponses,
  Post1AppliancesByApplianceidLightResponses,
  Post1AppliancesByApplianceidPowerDistBoardChannelData,
  Post1AppliancesByApplianceidPowerDistBoardChannelResponses,
  Post1AppliancesByApplianceidResponses,
  Post1AppliancesByApplianceidSesameBotClickData,
  Post1AppliancesByApplianceidSesameBotClickResponses,
  Post1AppliancesByApplianceidSignalOrdersData,
  Post1AppliancesByApplianceidSignalOrdersResponses,
  Post1AppliancesByApplianceidSignalsData,
  Post1AppliancesByApplianceidSignalsResponses,
  Post1AppliancesByApplianceidTvData,
  Post1AppliancesByApplianceidTvResponses,
  Post1AppliancesData,
  Post1AppliancesResponses,
  Post1BlePrivateMacrosByPrivatemacroidExecData,
  Post1BlePrivateMacrosByPrivatemacroidExecResponses,
  Post1DetectapplianceData,
  Post1DetectapplianceResponses,
  Post1DevicesByDeviceidData,
  Post1DevicesByDeviceidDeleteData,
  Post1DevicesByDeviceidDeleteResponses,
  Post1DevicesByDeviceidHumidityOffsetData,
  Post1DevicesByDeviceidHumidityOffsetResponses,
  Post1DevicesByDeviceidResponses,
  Post1DevicesByDeviceidTemperatureOffsetData,
  Post1DevicesByDeviceidTemperatureOffsetResponses,
  Post1EchonetliteAppliancesByApplianceidRefreshData,
  Post1EchonetliteAppliancesByApplianceidRefreshResponses,
  Post1EchonetliteAppliancesByApplianceidSetData,
  Post1EchonetliteAppliancesByApplianceidSetResponses,
  Post1EvccAppliancesByApplianceidStateData,
  Post1EvccAppliancesByApplianceidStateResponses,
  Post1HomesByHomeidData,
  Post1HomesByHomeidDeleteData,
  Post1HomesByHomeidDeleteResponses,
  Post1HomesByHomeidInvitesData,
  Post1HomesByHomeidInvitesResponses,
  Post1HomesByHomeidKickData,
  Post1HomesByHomeidKickResponses,
  Post1HomesByHomeidLocationData,
  Post1HomesByHomeidLocationDeleteData,
  Post1HomesByHomeidLocationDeleteResponses,
  Post1HomesByHomeidLocationResponses,
  Post1HomesByHomeidLocationStateUpdateData,
  Post1HomesByHomeidLocationStateUpdateResponses,
  Post1HomesByHomeidOwnerData,
  Post1HomesByHomeidOwnerResponses,
  Post1HomesByHomeidPartData,
  Post1HomesByHomeidPartResponses,
  Post1HomesByHomeidResponses,
  Post1HomesByHomeidTransferByTohomeidData,
  Post1HomesByHomeidTransferByTohomeidResponses,
  Post1HomesData,
  Post1HomesResponses,
  Post1InvitesByInvitetokenData,
  Post1InvitesByInvitetokenResponses,
  Post1SignalsBySignalidData,
  Post1SignalsBySignalidDeleteData,
  Post1SignalsBySignalidDeleteResponses,
  Post1SignalsBySignalidResponses,
  Post1SignalsBySignalidSendData,
  Post1SignalsBySignalidSendResponses,
  Post1UsersMeData,
  Post1UsersMeResponses,
  Post2AppliancesByApplianceidAirconSettingsData,
  Post2AppliancesByApplianceidAirconSettingsResponses,
  Post2DetectapplianceData,
  Post2DetectapplianceResponses,
} from "./types.gen";
import {
  vGet1AppliancesByApplianceidPowerDistBoardResponse,
  vGet1AppliancesByApplianceidSignalsResponse,
  vGet1AppliancesResponse,
  vGet1BleAppliancesByApplianceidPrivateMacrosResponse,
  vGet1DevicesByDeviceidAppliancesResponse,
  vGet1DevicesByDeviceidElectricityTimeSeriesHourlyResponse,
  vGet1DevicesResponse,
  vGet1EchonetliteAppliancesResponse,
  vGet1HomesByHomeidDevicesResponse,
  vGet1HomesByHomeidUsersResponse,
  vGet1HomesResponse,
  vGet1InvitesByInvitetokenResponse,
  vGet1UsersMeResponse,
  vPost1ApplianceOrdersResponse,
  vPost1AppliancesByApplianceidAirconSettingsResponse,
  vPost1AppliancesByApplianceidDeleteResponse,
  vPost1AppliancesByApplianceidFloorHeaterSettingsResponse,
  vPost1AppliancesByApplianceidLightProjectorResponse,
  vPost1AppliancesByApplianceidLightResponse,
  vPost1AppliancesByApplianceidPowerDistBoardChannelResponse,
  vPost1AppliancesByApplianceidResponse,
  vPost1AppliancesByApplianceidSesameBotClickResponse,
  vPost1AppliancesByApplianceidSignalOrdersResponse,
  vPost1AppliancesByApplianceidSignalsResponse,
  vPost1AppliancesByApplianceidTvResponse,
  vPost1AppliancesResponse,
  vPost1BlePrivateMacrosByPrivatemacroidExecResponse,
  vPost1DetectapplianceResponse,
  vPost1DevicesByDeviceidDeleteResponse,
  vPost1DevicesByDeviceidHumidityOffsetResponse,
  vPost1DevicesByDeviceidResponse,
  vPost1DevicesByDeviceidTemperatureOffsetResponse,
  vPost1EchonetliteAppliancesByApplianceidRefreshResponse,
  vPost1EchonetliteAppliancesByApplianceidSetResponse,
  vPost1EvccAppliancesByApplianceidStateResponse,
  vPost1HomesByHomeidDeleteResponse,
  vPost1HomesByHomeidInvitesResponse,
  vPost1HomesByHomeidKickResponse,
  vPost1HomesByHomeidLocationDeleteResponse,
  vPost1HomesByHomeidLocationResponse,
  vPost1HomesByHomeidLocationStateUpdateResponse,
  vPost1HomesByHomeidOwnerResponse,
  vPost1HomesByHomeidPartResponse,
  vPost1HomesByHomeidResponse,
  vPost1HomesByHomeidTransferByTohomeidResponse,
  vPost1HomesResponse,
  vPost1InvitesByInvitetokenResponse,
  vPost1SignalsBySignalidDeleteResponse,
  vPost1SignalsBySignalidResponse,
  vPost1SignalsBySignalidSendResponse,
  vPost1UsersMeResponse,
  vPost2AppliancesByApplianceidAirconSettingsResponse,
  vPost2DetectapplianceResponse,
} from "./valibot.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Reorder appliances.
 * Requires basic.write OAuth2 scopes.
 */
export const post1ApplianceOrders = <ThrowOnError extends boolean = true>(
  options: Options<Post1ApplianceOrdersData, ThrowOnError>,
): RequestResult<Post1ApplianceOrdersResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1ApplianceOrdersResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1ApplianceOrdersResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliance_orders",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the list of appliances.
 * Requires basic.read OAuth2 scopes.
 */
export const get1Appliances = <ThrowOnError extends boolean = true>(
  options?: Options<Get1AppliancesData, ThrowOnError>,
): RequestResult<Get1AppliancesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<Get1AppliancesResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1AppliancesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances",
    ...options,
  });

/**
 * Create a new appliance.
 * Requires basic.write OAuth2 scopes.
 */
export const post1Appliances = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesData, ThrowOnError>,
): RequestResult<Post1AppliancesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1AppliancesResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1AppliancesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update an appliance.
 * Requires basic.write OAuth2 scopes.
 */
export const post1AppliancesByApplianceid = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1AppliancesByApplianceidResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update air conditioner settings.
 * Requires sendir OAuth2 scopes.
 */
export const post1AppliancesByApplianceidAirconSettings = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidAirconSettingsData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidAirconSettingsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidAirconSettingsResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidAirconSettingsResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/aircon_settings",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Delete an appliance.
 * Requires basic.write OAuth2 scopes.
 */
export const post1AppliancesByApplianceidDelete = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidDeleteData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidDeleteResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidDeleteResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidDeleteResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/delete",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update floor heater settings.
 * Requires sendir OAuth2 scopes.
 */
export const post1AppliancesByApplianceidFloorHeaterSettings = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Post1AppliancesByApplianceidFloorHeaterSettingsData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidFloorHeaterSettingsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidFloorHeaterSettingsResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidFloorHeaterSettingsResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/floor_heater_settings",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Send light signal.
 * Requires sendir OAuth2 scopes.
 */
export const post1AppliancesByApplianceidLight = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidLightData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidLightResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidLightResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidLightResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/light",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Send light_projector signal.
 * Requires sendir OAuth2 scopes.
 */
export const post1AppliancesByApplianceidLightProjector = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidLightProjectorData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidLightProjectorResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidLightProjectorResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidLightProjectorResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/light_projector",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the power distribution board dashboard for an appliance.
 * Requires basic.read OAuth2 scopes.
 */
export const get1AppliancesByApplianceidPowerDistBoard = <ThrowOnError extends boolean = true>(
  options: Options<Get1AppliancesByApplianceidPowerDistBoardData, ThrowOnError>,
): RequestResult<Get1AppliancesByApplianceidPowerDistBoardResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    Get1AppliancesByApplianceidPowerDistBoardResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vGet1AppliancesByApplianceidPowerDistBoardResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/power_dist_board",
    ...options,
  });

/**
 * Update a power distribution board channel name.
 * Requires basic.write OAuth2 scopes.
 */
export const post1AppliancesByApplianceidPowerDistBoardChannel = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Post1AppliancesByApplianceidPowerDistBoardChannelData, ThrowOnError>,
): RequestResult<
  Post1AppliancesByApplianceidPowerDistBoardChannelResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidPowerDistBoardChannelResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidPowerDistBoardChannelResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/power_dist_board/channel",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Send SESAME bot click request.
 * Requires sendir OAuth2 scopes.
 */
export const post1AppliancesByApplianceidSesameBotClick = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidSesameBotClickData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidSesameBotClickResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidSesameBotClickResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidSesameBotClickResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/sesame_bot/click",
    ...options,
  });

/**
 * Reorder signals.
 * Requires basic.write OAuth2 scopes.
 */
export const post1AppliancesByApplianceidSignalOrders = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidSignalOrdersData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidSignalOrdersResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidSignalOrdersResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidSignalOrdersResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/signal_orders",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the list of signals.
 * Requires basic.read OAuth2 scopes.
 */
export const get1AppliancesByApplianceidSignals = <ThrowOnError extends boolean = true>(
  options: Options<Get1AppliancesByApplianceidSignalsData, ThrowOnError>,
): RequestResult<Get1AppliancesByApplianceidSignalsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    Get1AppliancesByApplianceidSignalsResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vGet1AppliancesByApplianceidSignalsResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/signals",
    ...options,
  });

/**
 * Create a new signal.
 * Requires basic.write OAuth2 scopes.
 */
export const post1AppliancesByApplianceidSignals = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidSignalsData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidSignalsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1AppliancesByApplianceidSignalsResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidSignalsResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/signals",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Send TV signal.
 * Requires sendir OAuth2 scopes.
 */
export const post1AppliancesByApplianceidTv = <ThrowOnError extends boolean = true>(
  options: Options<Post1AppliancesByApplianceidTvData, ThrowOnError>,
): RequestResult<Post1AppliancesByApplianceidTvResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1AppliancesByApplianceidTvResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1AppliancesByApplianceidTvResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/appliances/{applianceid}/tv",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the list of ble_private_macros.
 * Requires basic.read OAuth2 scopes.
 */
export const get1BleAppliancesByApplianceidPrivateMacros = <ThrowOnError extends boolean = true>(
  options: Options<Get1BleAppliancesByApplianceidPrivateMacrosData, ThrowOnError>,
): RequestResult<Get1BleAppliancesByApplianceidPrivateMacrosResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<
    Get1BleAppliancesByApplianceidPrivateMacrosResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vGet1BleAppliancesByApplianceidPrivateMacrosResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/ble/appliances/{applianceid}/private_macros",
    ...options,
  });

/**
 * Send BLE Private Macro control request.
 * Requires sendir OAuth2 scopes.
 */
export const post1BlePrivateMacrosByPrivatemacroidExec = <ThrowOnError extends boolean = true>(
  options: Options<Post1BlePrivateMacrosByPrivatemacroidExecData, ThrowOnError>,
): RequestResult<Post1BlePrivateMacrosByPrivatemacroidExecResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1BlePrivateMacrosByPrivatemacroidExecResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vPost1BlePrivateMacrosByPrivatemacroidExecResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/ble/private_macros/{privatemacroid}/exec",
    ...options,
  });

/**
 * Find the air conditioner best matching the provided infrared signal.
 * Requires detectappliance OAuth2 scopes.
 */
export const post1Detectappliance = <ThrowOnError extends boolean = true>(
  options: Options<Post1DetectapplianceData, ThrowOnError>,
): RequestResult<Post1DetectapplianceResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1DetectapplianceResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1DetectapplianceResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/detectappliance",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the list of Remo devices.
 * Requires basic.read OAuth2 scopes.
 */
export const get1Devices = <ThrowOnError extends boolean = true>(
  options?: Options<Get1DevicesData, ThrowOnError>,
): RequestResult<Get1DevicesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<Get1DevicesResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1DevicesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/devices",
    ...options,
  });

/**
 * Update a device.
 * Requires basic.write OAuth2 scopes.
 */
export const post1DevicesByDeviceid = <ThrowOnError extends boolean = true>(
  options: Options<Post1DevicesByDeviceidData, ThrowOnError>,
): RequestResult<Post1DevicesByDeviceidResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1DevicesByDeviceidResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1DevicesByDeviceidResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/devices/{deviceid}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the list of appliances registered to the Remo device.
 * Requires basic.read OAuth2 scopes.
 */
export const get1DevicesByDeviceidAppliances = <ThrowOnError extends boolean = true>(
  options: Options<Get1DevicesByDeviceidAppliancesData, ThrowOnError>,
): RequestResult<Get1DevicesByDeviceidAppliancesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<Get1DevicesByDeviceidAppliancesResponses, unknown, ThrowOnError>({
    responseValidator: async (data) =>
      await v.parseAsync(vGet1DevicesByDeviceidAppliancesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/devices/{deviceid}/appliances",
    ...options,
  });

/**
 * Delete a device.
 * Requires basic.write OAuth2 scopes.
 */
export const post1DevicesByDeviceidDelete = <ThrowOnError extends boolean = true>(
  options: Options<Post1DevicesByDeviceidDeleteData, ThrowOnError>,
): RequestResult<Post1DevicesByDeviceidDeleteResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1DevicesByDeviceidDeleteResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1DevicesByDeviceidDeleteResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/devices/{deviceid}/delete",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch hourly electricity time series data.
 *
 * Returns hourly energy data for the appliances registered to the device.
 *
 * Each metric is a 2-element tuple `[unix time in seconds, value in kWh]`. The unix time marks the start of an hour: it always falls exactly on the hour (minutes and seconds are zero) on the Asia/Tokyo (JST) clock, and consecutive points are exactly one hour (3600 seconds) apart. The value is the energy accumulated during that hour, in kWh.
 * Requires electricity OAuth2 scopes.
 */
export const get1DevicesByDeviceidElectricityTimeSeriesHourly = <
  ThrowOnError extends boolean = true,
>(
  options: Options<Get1DevicesByDeviceidElectricityTimeSeriesHourlyData, ThrowOnError>,
): RequestResult<
  Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses,
  unknown,
  ThrowOnError
> =>
  (options.client ?? client).get<
    Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vGet1DevicesByDeviceidElectricityTimeSeriesHourlyResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/devices/{deviceid}/electricity/time_series/hourly",
    ...options,
  });

/**
 * Update a device's humidity offset.
 * Requires basic.write OAuth2 scopes.
 */
export const post1DevicesByDeviceidHumidityOffset = <ThrowOnError extends boolean = true>(
  options: Options<Post1DevicesByDeviceidHumidityOffsetData, ThrowOnError>,
): RequestResult<Post1DevicesByDeviceidHumidityOffsetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1DevicesByDeviceidHumidityOffsetResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1DevicesByDeviceidHumidityOffsetResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/devices/{deviceid}/humidity_offset",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update a device's temperature offset.
 * Requires basic.write OAuth2 scopes.
 */
export const post1DevicesByDeviceidTemperatureOffset = <ThrowOnError extends boolean = true>(
  options: Options<Post1DevicesByDeviceidTemperatureOffsetData, ThrowOnError>,
): RequestResult<Post1DevicesByDeviceidTemperatureOffsetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1DevicesByDeviceidTemperatureOffsetResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1DevicesByDeviceidTemperatureOffsetResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/devices/{deviceid}/temperature_offset",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the list of ECHONET Lite appliances.
 * Requires basic.read OAuth2 scopes.
 */
export const get1EchonetliteAppliances = <ThrowOnError extends boolean = true>(
  options?: Options<Get1EchonetliteAppliancesData, ThrowOnError>,
): RequestResult<Get1EchonetliteAppliancesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<Get1EchonetliteAppliancesResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1EchonetliteAppliancesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/echonetlite/appliances",
    ...options,
  });

/**
 * Notify Remo E / Remo E lite to refresh one or more ECHONET Lite properties. This endpoint is subject to ECHONET Lite specific rate limiting. See the rate limiting section of the documentation for more details.
 * Requires echonetlite.*.read OAuth2 scopes.
 */
export const post1EchonetliteAppliancesByApplianceidRefresh = <ThrowOnError extends boolean = true>(
  options: Options<Post1EchonetliteAppliancesByApplianceidRefreshData, ThrowOnError>,
): RequestResult<Post1EchonetliteAppliancesByApplianceidRefreshResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1EchonetliteAppliancesByApplianceidRefreshResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1EchonetliteAppliancesByApplianceidRefreshResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/echonetlite/appliances/{applianceid}/refresh",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Set one ECHONET Lite property. This endpoint is subject to ECHONET Lite specific rate limiting. See the rate limiting section of the documentation for more details.
 * Requires echonetlite.*.write OAuth2 scopes.
 */
export const post1EchonetliteAppliancesByApplianceidSet = <ThrowOnError extends boolean = true>(
  options: Options<Post1EchonetliteAppliancesByApplianceidSetData, ThrowOnError>,
): RequestResult<Post1EchonetliteAppliancesByApplianceidSetResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1EchonetliteAppliancesByApplianceidSetResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1EchonetliteAppliancesByApplianceidSetResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/echonetlite/appliances/{applianceid}/set",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update the relay state of the Nature EV Switch.
 *
 *
 * Requires nature_evcc OAuth2 scopes.
 */
export const post1EvccAppliancesByApplianceidState = <ThrowOnError extends boolean = true>(
  options: Options<Post1EvccAppliancesByApplianceidStateData, ThrowOnError>,
): RequestResult<Post1EvccAppliancesByApplianceidStateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1EvccAppliancesByApplianceidStateResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vPost1EvccAppliancesByApplianceidStateResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/evcc/appliances/{applianceid}/state",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Fetch the list of homes.
 * Requires basic.read OAuth2 scopes.
 */
export const get1Homes = <ThrowOnError extends boolean = true>(
  options?: Options<Get1HomesData, ThrowOnError>,
): RequestResult<Get1HomesResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<Get1HomesResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1HomesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes",
    ...options,
  });

/**
 * Create a new home.
 * Requires home.write OAuth2 scopes.
 */
export const post1Homes = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesData, ThrowOnError>,
): RequestResult<Post1HomesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1HomesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update a home.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeid = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1HomesByHomeidResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Delete a home.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidDelete = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidDeleteData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidDeleteResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidDeleteResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vPost1HomesByHomeidDeleteResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/delete",
    ...options,
  });

/**
 * Fetch the list of devices in a home.
 * Requires basic.read OAuth2 scopes.
 */
export const get1HomesByHomeidDevices = <ThrowOnError extends boolean = true>(
  options: Options<Get1HomesByHomeidDevicesData, ThrowOnError>,
): RequestResult<Get1HomesByHomeidDevicesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<Get1HomesByHomeidDevicesResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1HomesByHomeidDevicesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/devices",
    ...options,
  });

/**
 * Create a new home invite.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidInvites = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidInvitesData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidInvitesResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidInvitesResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vPost1HomesByHomeidInvitesResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/invites",
    ...options,
  });

/**
 * Kick a user from a home.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidKick = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidKickData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidKickResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidKickResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1HomesByHomeidKickResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/kick",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update a home's location.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidLocation = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidLocationData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidLocationResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidLocationResponses, unknown, ThrowOnError>({
    responseValidator: async (data) =>
      await v.parseAsync(vPost1HomesByHomeidLocationResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/location",
    ...options,
  });

/**
 * Delete a home's location.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidLocationDelete = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidLocationDeleteData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidLocationDeleteResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidLocationDeleteResponses, unknown, ThrowOnError>(
    {
      ...urlSearchParamsBodySerializer,
      responseValidator: async (data) =>
        await v.parseAsync(vPost1HomesByHomeidLocationDeleteResponse, data),
      security: [{ scheme: "bearer", type: "http" }],
      url: "/1/homes/{homeid}/location/delete",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    },
  );

/**
 * Update the user's location state for a home.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidLocationStateUpdate = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidLocationStateUpdateData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidLocationStateUpdateResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1HomesByHomeidLocationStateUpdateResponses,
    unknown,
    ThrowOnError
  >({
    responseValidator: async (data) =>
      await v.parseAsync(vPost1HomesByHomeidLocationStateUpdateResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/location_state/update",
    ...options,
  });

/**
 * Change the owner of the home.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidOwner = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidOwnerData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidOwnerResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidOwnerResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1HomesByHomeidOwnerResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/owner",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Part from a home.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidPart = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidPartData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidPartResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1HomesByHomeidPartResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vPost1HomesByHomeidPartResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/part",
    ...options,
  });

/**
 * Transfer devices to another home.
 * Requires home.write OAuth2 scopes.
 */
export const post1HomesByHomeidTransferByTohomeid = <ThrowOnError extends boolean = true>(
  options: Options<Post1HomesByHomeidTransferByTohomeidData, ThrowOnError>,
): RequestResult<Post1HomesByHomeidTransferByTohomeidResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post1HomesByHomeidTransferByTohomeidResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1HomesByHomeidTransferByTohomeidResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/transfer/{tohomeid}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the list of users in a home.
 * Requires basic.read OAuth2 scopes.
 */
export const get1HomesByHomeidUsers = <ThrowOnError extends boolean = true>(
  options: Options<Get1HomesByHomeidUsersData, ThrowOnError>,
): RequestResult<Get1HomesByHomeidUsersResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<Get1HomesByHomeidUsersResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1HomesByHomeidUsersResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/homes/{homeid}/users",
    ...options,
  });

/**
 * Show a home invite.
 * Requires home.read OAuth2 scopes.
 */
export const get1InvitesByInvitetoken = <ThrowOnError extends boolean = true>(
  options: Options<Get1InvitesByInvitetokenData, ThrowOnError>,
): RequestResult<Get1InvitesByInvitetokenResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<Get1InvitesByInvitetokenResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1InvitesByInvitetokenResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/invites/{invitetoken}",
    ...options,
  });

/**
 * Accept a home invite.
 * Requires home.write OAuth2 scopes.
 */
export const post1InvitesByInvitetoken = <ThrowOnError extends boolean = true>(
  options: Options<Post1InvitesByInvitetokenData, ThrowOnError>,
): RequestResult<Post1InvitesByInvitetokenResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1InvitesByInvitetokenResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vPost1InvitesByInvitetokenResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/invites/{invitetoken}",
    ...options,
  });

/**
 * Update a signal.
 * Requires basic.write OAuth2 scopes.
 */
export const post1SignalsBySignalid = <ThrowOnError extends boolean = true>(
  options: Options<Post1SignalsBySignalidData, ThrowOnError>,
): RequestResult<Post1SignalsBySignalidResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1SignalsBySignalidResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1SignalsBySignalidResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/signals/{signalid}",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Delete a signal.
 * Requires basic.write OAuth2 scopes.
 */
export const post1SignalsBySignalidDelete = <ThrowOnError extends boolean = true>(
  options: Options<Post1SignalsBySignalidDeleteData, ThrowOnError>,
): RequestResult<Post1SignalsBySignalidDeleteResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1SignalsBySignalidDeleteResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1SignalsBySignalidDeleteResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/signals/{signalid}/delete",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Send a signal.
 * Requires sendir OAuth2 scopes.
 */
export const post1SignalsBySignalidSend = <ThrowOnError extends boolean = true>(
  options: Options<Post1SignalsBySignalidSendData, ThrowOnError>,
): RequestResult<Post1SignalsBySignalidSendResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1SignalsBySignalidSendResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost1SignalsBySignalidSendResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/signals/{signalid}/send",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Fetch the authenticated user's information.
 * Requires basic.read OAuth2 scopes.
 */
export const get1UsersMe = <ThrowOnError extends boolean = true>(
  options?: Options<Get1UsersMeData, ThrowOnError>,
): RequestResult<Get1UsersMeResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<Get1UsersMeResponses, unknown, ThrowOnError>({
    responseValidator: async (data) => await v.parseAsync(vGet1UsersMeResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/users/me",
    ...options,
  });

/**
 * Update authenticated user's information.
 * Requires basic.write OAuth2 scopes.
 */
export const post1UsersMe = <ThrowOnError extends boolean = true>(
  options: Options<Post1UsersMeData, ThrowOnError>,
): RequestResult<Post1UsersMeResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post1UsersMeResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost1UsersMeResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/1/users/me",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Update air conditioner settings.
 * Requires sendir OAuth2 scopes.
 */
export const post2AppliancesByApplianceidAirconSettings = <ThrowOnError extends boolean = true>(
  options: Options<Post2AppliancesByApplianceidAirconSettingsData, ThrowOnError>,
): RequestResult<Post2AppliancesByApplianceidAirconSettingsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<
    Post2AppliancesByApplianceidAirconSettingsResponses,
    unknown,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) =>
      await v.parseAsync(vPost2AppliancesByApplianceidAirconSettingsResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/2/appliances/{applianceid}/aircon_settings",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });

/**
 * Find the air conditioner best matching the provided infrared signal. Returns a unified response with results, suggested_action, and session_token.
 * Requires detectappliance OAuth2 scopes.
 */
export const post2Detectappliance = <ThrowOnError extends boolean = true>(
  options: Options<Post2DetectapplianceData, ThrowOnError>,
): RequestResult<Post2DetectapplianceResponses, unknown, ThrowOnError> =>
  (options.client ?? client).post<Post2DetectapplianceResponses, unknown, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseValidator: async (data) => await v.parseAsync(vPost2DetectapplianceResponse, data),
    security: [{ scheme: "bearer", type: "http" }],
    url: "/2/detectappliance",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
