// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.nature.global" | (string & {});
};

export type Addr = string;

export type AirConExtraResponse = {
  availability: string;
  defaultTime?: string;
  description: string;
  id: string;
  options?: Array<ExtraOption> | null;
  text: string;
  type: string;
};

export type AirConParams = {
  /**
   * AC air direction. Empty means automatic.
   */
  air_direction: string;
  /**
   * AC horizontal air direction.
   */
  air_direction_h: string;
  /**
   * AC air volume. Empty means automatic. Numbers express the amount of volume. The range of AirVolumes which the air conditioner accepts depends on the air conditioner model and operation mode. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model and operation mode.
   */
  air_volume: string;
  /**
   * Button. Specify 'power-off' always if you want the air conditioner powered off. Empty means powered on.
   */
  button: string;
  /**
   * AC specific parameters. Pass device-specific options through the extra query string in the form extra.$id=$value. Valid id / value pairs correspond to the entries returned in ApplianceResponse.extras. Only IDs whose availability field is available may be specified.
   */
  extra?: {
    [key: string]: string;
  } | null;
  /**
   * AC operation mode. The range of operation modes which the air conditioner accepts depends on the air conditioner model. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model.
   */
  operation_mode: string;
  /**
   * Temperature. The temperature in string format. The unit is described in Aircon object. The range of Temperatures which the air conditioner accepts depends on the air conditioner model and operation mode. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model and operation mode.
   */
  temperature: string;
  /**
   * Temperature unit. 'c' or 'f' or '' for unknown.
   */
  temperature_unit: string;
};

export type AirConRangeResponse = {
  extras?: Array<AirConExtraResponse> | null;
  fixedButtons: Array<string> | null;
  modes: {
    [key: string]: RangeResponseMode;
  } | null;
};

export type AirConResponse = {
  range: AirConRangeResponse;
  tempUnit: string;
};

export type AirDirectionHRange = Array<string> | null;

export type AirDirectionRange = Array<string> | null;

export type AirVolumeRange = Array<string> | null;

export type AirconSemResponse = {
  adjusting: boolean;
  area: Area;
  campaign_slug: CampaignSlug;
  enabled: boolean;
};

export type AirconSettingsResponse = {
  /**
   * Button. Specify 'power-off' always if you want the air conditioner powered off. Empty means powered on.
   */
  button: string;
  /**
   * AC air direction. Empty means automatic.
   */
  dir: string;
  /**
   * AC horizontal air direction.
   */
  dirh: string;
  /**
   * AC specific parameters. Pass device-specific options through the extra query string in the form extra.$id=$value. Valid id / value pairs correspond to the entries returned in ApplianceResponse.extras. Only IDs whose availability field is available may be specified.
   */
  extra?: {
    [key: string]: string;
  } | null;
  /**
   * AC operation mode. The range of operation modes which the air conditioner accepts depends on the air conditioner model. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model.
   */
  mode: string;
  /**
   * Temperature. The temperature in string format. The unit is described in Aircon object. The range of Temperatures which the air conditioner accepts depends on the air conditioner model and operation mode. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model and operation mode.
   */
  temp: string;
  /**
   * Temperature unit. 'c' or 'f' or '' for unknown.
   */
  temp_unit: string;
  updated_at: Time;
  /**
   * AC air volume. Empty means automatic. Numbers express the amount of volume. The range of AirVolumes which the air conditioner accepts depends on the air conditioner model and operation mode. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model and operation mode.
   */
  vol: string;
};

export type ApplianceElModel = {
  id: string;
  image: string;
  manufacturer: string;
  name: string;
};

export type ApplianceFloorHeaterModel = {
  country: string;
  id: string;
  image: string;
  manufacturer: string;
  name: string;
  remote_name: string;
  series: string;
};

export type ApplianceLightModel = {
  country: string;
  id: string;
  image: string;
  manufacturer: string;
  name: string;
  remote_name: string;
};

export type ApplianceLightProjectorModel = {
  country: string;
  id: string;
  image: string;
  manufacturer: string;
  name: string;
  remote_name: string;
};

export type ApplianceModel = {
  country: string;
  id: string;
  image: string;
  manufacturer: string;
  name: string;
  remote_name: string;
  series: string;
};

export type ApplianceModelAndParam = {
  model: ApplianceModel;
  params: Params;
};

export type ApplianceModelAndParams = Array<ApplianceModelAndParam> | null;

export type ApplianceModelUnion =
  | ApplianceModel
  | ApplianceTvModel
  | ApplianceLightModel
  | ApplianceElModel
  | ApplianceLightProjectorModel
  | ApplianceFloorHeaterModel
  | BleModel
  | null;

export type ApplianceResponse = {
  aircon?: AirConResponse | null;
  aircon_smart_eco_mode?: AirconSemResponse | null;
  ble?: BleControlItem | null;
  /**
   * The device used to control this appliance. If not bound to a controller device, this represents the device information of the appliance itself.
   */
  device?: Device | null;
  /**
   * The ECHONET lite properties fetched from the appliance. See 'Detailed Requirements for ECHONET Device Objects' for more details. ref. https://echonet.jp/spec_object_rl_en/
   */
  echonetlite?: ElResponse | null;
  evcc?: EvccResponse | null;
  floor_heater?: FloorHeaterResponse | null;
  id: string;
  image: string;
  light?: LightResponse | null;
  light_projector?: LightProjectorResponse | null;
  matter_bridged_device_state?: string | null;
  model: ApplianceModelUnion;
  mornin_plus?: MorninPlusResponse | null;
  nickname: string;
  qrio_lock?: QrioLockResponse | null;
  settings?: AirconSettingsResponse | null;
  signals: Array<Signal> | null;
  smart_meter?: SmartMeterResponse | null;
  tv?: TvResponse | null;
  type: string;
};

export type ApplianceResponses = Array<ApplianceResponse> | null;

export type ApplianceTvModel = {
  country: string;
  id: string;
  image: string;
  manufacturer: string;
  name: string;
  remote_name: string;
};

export type AppliancesDetectApplianceV2Request = {
  /**
   * Device UUID. If specified, the detection result will be filtered by device capability.
   */
  Device?: string | null;
  /**
   * JSON serialized object describing infrared signals. Includes 'data', 'freq' and 'format' keys.
   */
  Message: string;
  /**
   * Session token returned by a previous DetectApplianceV2 call. If provided, the server uses the previous detection session to narrow down candidates.
   */
  SessionToken: string;
};

export type AppliancesDetectApplianceV2Response = {
  results: Array<ApplianceModelAndParam> | null;
  session_token: string;
  suggested_action: string;
  suggested_action_message: string;
};

export type AppliancesUpdateRequest = {
  /**
   * Basename of the image file included in the app. Ex: 'ico_ac_1'.
   */
  image: string;
  /**
   * Appliance name.
   */
  nickname: string;
};

export type Area = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export type BleControlItem = {
  addr: string;
  addr_type: string;
  bonded: boolean;
  hue?: BleHueLightControlItem | null;
  macros?: {
    [key: string]: BlePrivateMacroResponse;
  } | null;
  sesame?: BleSesameControlItem | null;
};

export type BleHueLightControlItem = {
  light_type: string;
};

export type BleModel = {
  id: string;
  image: string;
  name: string;
  slug: string;
};

export type BlePrivateMacroResponse = {
  id: string;
  url: string;
};

export type BlePrivateMacroResponses = Array<BlePrivateMacroResponse> | null;

export type BleSesameControlItem = {
  device_type: string;
  key_level: string;
  user_index: Array<number> | null;
  uuid: string;
};

export type ButtonDbButton = {
  image: string;
  label: string;
  name: string;
};

export type CampaignSlug = string;

/**
 * Breaker capacity in amperes (A). Must be between 10 and 200.
 */
export type CoreHomeBreakerCapacity = number;

export type CoreSensorValue = {
  created_at: Time;
  val: number;
};

/**
 * Serial number of the device.
 */
export type CoreSerialNumber = string;

export type CreateApplianceRequest = {
  device: string;
  /**
   * Basename of the image file included in the app. Ex: 'ico_ac_1'.
   */
  image: string;
  /**
   * ApplianceModel ID if the appliance we're trying to create is included in IRDB.
   */
  model: string;
  /**
   * Enum of 'AC', 'TV', 'Light', etc.
   */
  model_type: string;
  /**
   * Appliance name.
   */
  nickname: string;
};

export type CreateSignalParameters = {
  /**
   * Basename of the image file included in the app. Ex: 'ico_io'.
   */
  image: string;
  /**
   * JSON serialized object describing infrared signals. Includes 'data', 'freq' and 'format' keys.
   */
  message: string;
  /**
   * Signal name.
   */
  name: string;
};

export type DetectApplianceRequest = {
  /**
   * Device UUID. If specified, the detection result will be filtered by device capability.
   */
  Device?: string | null;
  /**
   * JSON serialized object describing infrared signals. Includes 'data', 'freq' and 'format' keys.
   */
  Message: string;
};

export type Device = {
  bt_mac_address?: string | null;
  created_at: Time;
  firmware_version: string;
  humidity_offset: number;
  id: string;
  mac_address: string;
  name: string;
  serial_number: CoreSerialNumber;
  temperature_offset: number;
  updated_at: Time;
};

export type DeviceCommissioneeFabricResponse = {
  cfabric: string;
  company_name: string;
  label: string;
  vendor_name: string;
};

export type DeviceEnergyTimeSeries = {
  from_evcd?: Metrics;
  from_fuel_cell?: Metrics;
  from_grid?: Metrics;
  from_solar_power?: Metrics;
  from_storage_battery?: Metrics;
  home_consumed?: Metrics;
  to_evcc?: Metrics;
  to_evcd?: Metrics;
  to_grid?: Metrics;
  to_storage_battery?: Metrics;
};

export type DeviceResponse = {
  bridged_devices_limit?: number | null;
  bt_mac_address?: string | null;
  commissionee_fabrics?: Array<DeviceCommissioneeFabricResponse> | null;
  commissionee_fabrics_limit?: number | null;
  created_at: Time;
  firmware_version: string;
  humidity_offset: number;
  id: string;
  mac_address: string;
  name: string;
  /**
   * The SensorValue key means 'te' = temperature, 'hu' = humidity, 'il' = illumination, 'mo' = movement. The val of 'mo' is always 1 and when movement event is captured created_at is updated.
   */
  newest_events: {
    [key: string]: CoreSensorValue;
  } | null;
  online?: boolean | null;
  serial_number: CoreSerialNumber;
  temperature_offset: number;
  updated_at: Time;
  /**
   * Deprecated. Do not use in new code.
   */
  users?: Array<UserDeviceResponse> | null;
};

export type DeviceResponses = Array<DeviceResponse> | null;

export type DevicesDeleteRequest = {
  [key: string]: unknown;
};

export type DevicesDeleteResponse = {
  [key: string]: unknown;
};

export type DevicesUpdateRequest = {
  name: string;
};

export type ElManufacturer = {
  code: string;
  name: string;
};

export type ElPropertyResponse = {
  epc: number;
  name: string;
  updated_at: Time;
  val: string;
};

export type ElResponse = {
  identifier: string;
  instance: string;
  ip?: string | null;
  manufacturer: ElManufacturer;
  route_type: string;
  version: string;
};

export type EvccAutoRecoveringValueUnion =
  | ({
      kind: "abnormal_temperature";
    } & EvccStateErrorValueAbnormalTemperature)
  | ({
      kind: "warnings";
    } & EvccStateErrorValueWarnings);

export type EvccResponse = {
  connected_device?: Device | null;
  current_charging_amount?: number | null;
  errors?: EvccStateErrorsResponse | null;
  last_operated_remotely: boolean;
  online: ValueUpdatedAtBool;
  relay_state: ValueUpdatedAtEvccRelayState;
  vehicle: Vehicle;
};

export type EvccSelfTestValueUnion =
  | ({
      kind: "relay";
    } & EvccStateErrorValueRelay)
  | ({
      kind: "meter";
    } & EvccStateErrorValueMeter)
  | ({
      kind: "meter_communication";
    } & EvccStateErrorValueMeterCommunication)
  | ({
      kind: "memory";
    } & EvccStateErrorValueMemory)
  | ({
      kind: "unrecoverable";
    } & EvccStateErrorValueUnrecoverable);

export type EvccStateErrorValueAbnormalTemperature = {
  kind: "abnormal_temperature";
  type: "over_temperature" | "unknown";
};

export type EvccStateErrorValueMemory = {
  kind: "memory";
  type:
    | "read_status_error"
    | "write_status_error"
    | "read_energy_error"
    | "write_energy_error"
    | "unknown";
};

export type EvccStateErrorValueMeter = {
  kind: "meter";
  type: "overvoltage" | "undervoltage" | "overcurrent" | "energy_leak" | "unknown";
};

export type EvccStateErrorValueMeterCommunication = {
  kind: "meter_communication";
  type: "serial_error" | "unknown";
};

export type EvccStateErrorValueRelay = {
  kind: "relay";
  type: "conflict" | "unknown";
};

export type EvccStateErrorValueUnrecoverable = {
  kind: "unrecoverable";
  type:
    | "boot_error"
    | "self_test_under_fatal_error_failed"
    | "emergency_stop_from_server"
    | "unknown";
};

export type EvccStateErrorValueWarnings = {
  kind: "warnings";
  type: "over_current_warning" | "unknown";
};

export type EvccStateErrorsResponse = {
  auto_recovering: Array<ValueUpdatedAtEvccAutoRecoveringValueUnion> | null;
  require_self_test: Array<ValueUpdatedAtEvccSelfTestValueUnion> | null;
};

export type EchonetLiteAppliance = {
  Device?: Device | null;
  id: string;
  nickname: string;
  properties: Array<PropertyRow> | null;
  type: string;
};

export type EchonetLiteApplianceResponse = {
  appliances: Array<EchonetLiteAppliance> | null;
};

export type EmptyObject = {
  [key: string]: unknown;
};

export type ExtraOption = {
  default?: boolean;
  text: ExtraOptionText;
  value: string;
};

export type ExtraOptionText = string;

export type FloorHeaterResponse = {
  range: AirConRangeResponse;
  tempUnit: string;
};

export type HexBytes = Array<number> | null;

export type Home = {
  breaker_capacity?: CoreHomeBreakerCapacity | null;
  id: string;
  name: string;
};

export type HomeInvite = {
  home?: Home | null;
  url: string;
  user?: User | null;
};

export type HomeParams = {
  name: string;
};

export type HomeResponse = {
  breaker_capacity?: CoreHomeBreakerCapacity | null;
  id: string;
  name: string;
  users: Array<MemberResponse> | null;
};

export type HomeResponses = Array<HomeResponse> | null;

export type HomeUserParams = {
  user: string;
};

export type HomesDeleteLocationRequest = {
  [key: string]: unknown;
};

export type HomesDeleteLocationResponse = {
  breaker_capacity?: CoreHomeBreakerCapacity | null;
  id: string;
  name: string;
  users: Array<MemberResponse> | null;
};

export type HumidityOffsetParams = {
  /**
   * Humidity offset value added to the measured humidity.
   */
  offset: number;
};

export type LightParams = {
  /**
   * Button name.
   */
  button: string;
};

export type LightProjectorParams = {
  /**
   * Button name.
   */
  button: string;
};

export type LightProjectorResponse = {
  layout: LightProjectordbLayout;
};

export type LightProjectordbLayout = {
  image: string;
  label: string;
  name: string;
  templates: Array<Template | null> | null;
  text: string;
  type: string;
  uuid: string;
  x_size: number;
  y_size: number;
};

export type LightResponse = {
  buttons: Array<ButtonDbButton> | null;
  state?: LightState | null;
};

export type LightState = {
  brightness: string;
  last_button: string;
  power: string;
};

export type LinkText = {
  link: string;
  text: string;
};

export type MemberResponse = {
  id: string;
  joined_at: Time;
  location_state: string;
  nickname: string;
  role: string;
};

/**
 * Time series of metrics. Each element is a 2-element tuple [unix time in seconds, value in kWh]. e.g. [1700000000, 1.234]
 */
export type Metrics = Array<[number, number]>;

export type MorninPlusDeviceResponse = {
  active: boolean;
  id: string;
  image: string;
  name: string;
};

export type MorninPlusResponse = {
  devices: Array<MorninPlusDeviceResponse | null> | null;
  hi_speed_mode: boolean;
};

export type Params = {
  /**
   * Button. Specify 'power-off' always if you want the air conditioner powered off. Empty means powered on.
   */
  button: string;
  /**
   * AC air direction. Empty means automatic.
   */
  dir: string;
  /**
   * AC horizontal air direction.
   */
  dirh: string;
  /**
   * AC specific parameters. Pass device-specific options through the extra query string in the form extra.$id=$value. Valid id / value pairs correspond to the entries returned in ApplianceResponse.extras. Only IDs whose availability field is available may be specified.
   */
  extra?: {
    [key: string]: string;
  } | null;
  /**
   * AC operation mode. The range of operation modes which the air conditioner accepts depends on the air conditioner model. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model.
   */
  mode: string;
  /**
   * Temperature. The temperature in string format. The unit is described in Aircon object. The range of Temperatures which the air conditioner accepts depends on the air conditioner model and operation mode. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model and operation mode.
   */
  temp: string;
  /**
   * Temperature unit. 'c' or 'f' or '' for unknown.
   */
  temp_unit: string;
  /**
   * AC air volume. Empty means automatic. Numbers express the amount of volume. The range of AirVolumes which the air conditioner accepts depends on the air conditioner model and operation mode. Check the 'AirConRangeMode' information in the response for the range of the particular air conditioner model and operation mode.
   */
  vol: string;
};

export type PowerdistboardBoard = {
  /**
   * List of channels
   */
  channels: Array<PowerdistboardChannel> | null;
};

export type PowerdistboardChannel = {
  /**
   * Appliance name (max 40 chars)
   */
  appliance_name: string;
  /**
   * Channel number (1-252)
   */
  number: number;
  /**
   * Room name (max 40 chars)
   */
  room_name: string;
};

export type PowerdistboardDashboard = {
  /**
   * Channel name options
   */
  options: PowerdistboardOptions;
  /**
   * Power distribution board data
   */
  power_dist_board: PowerdistboardBoard;
};

export type PowerdistboardOptions = {
  /**
   * Appliance name options
   */
  appliance_names: Array<string> | null;
  /**
   * Room name options
   */
  room_names: Array<string> | null;
};

export type PrivacyPolicyRevisionOutline = {
  body: string;
  links: {
    [key: string]: LinkText;
  } | null;
  title: string;
};

export type PropertyRow = {
  epc: string;
  updated_at: Time;
  val: string;
};

export type QrioLockDeviceResponse = {
  id: number;
  image: string;
  name: string;
};

export type QrioLockResponse = {
  bd_address: string;
  device: QrioLockDeviceResponse;
  is_available: boolean;
  sub_bd_address?: string;
};

export type RangeResponseMode = {
  dir: Array<string> | null;
  dirh: Array<string> | null;
  temp: Array<string> | null;
  vol: Array<string> | null;
};

export type RefreshElPropertyRequest = {
  /**
   * Comma separated EPCs in hex. eg: cf,da
   */
  epc: string;
};

export type ReorderAppliancesParams = {
  /**
   * List of all appliance IDs, comma separated.
   */
  appliances: string;
};

export type ReorderSignalsParams = {
  /**
   * List of all signal IDs, comma separated.
   */
  signals: string;
};

export type SetElPropertyRequest = {
  /**
   * EPC in hex string. eg: cf
   */
  epc: string;
  /**
   * Value in hex string. String length must be 2x the number of bytes according to ECHONET Lite spec, and filled with zero if necessary. eg: 000000FF
   */
  val: string;
};

export type Signal = {
  id: string;
  image: string;
  name: string;
};

export type Signals = Array<Signal> | null;

export type SmartMeterResponse = {
  echonetlite_properties: Array<ElPropertyResponse | null> | null;
};

export type TvParams = {
  /**
   * Button name.
   */
  button: string;
};

export type TvResponse = {
  buttons: Array<ButtonDbButton> | null;
  layout?: Array<TvdbRowLayout> | null;
  state?: TvState | null;
};

export type TvState = {
  input: string;
};

export type TemperatureOffsetParams = {
  /**
   * Temperature offset value added to the measured temperature.
   */
  offset: number;
};

export type Template = {
  image: string;
  label: string;
  name: string;
  templates: Array<Template | null> | null;
  text: string;
  type: string;
  uuid: string;
  x_size: number;
  y_size: number;
};

export type Time = string;

export type TransferRequest = {
  devices: string;
};

export type TvdbRowLayout = {
  buttons: Array<string> | null;
  type: string;
};

export type Uuid = string;

export type UpdateEvccRelayState = "open" | "close";

export type UpdateEvccStateRequest = {
  relay_state: UpdateEvccRelayState;
};

export type UpdateProfileParam = {
  country: string;
  distance_unit: string;
  nickname: string;
  temp_unit: string;
};

export type UpdateSignalParameters = {
  /**
   * Basename of the image file included in the app. Ex: 'ico_io'.
   */
  image: string;
  /**
   * Signal name.
   */
  name: string;
};

export type User = {
  id: string;
  nickname: string;
};

export type UserAndRole = {
  role: string;
  user: User;
};

export type UserAndRoles = Array<UserAndRole> | null;

export type UserDeviceResponse = {
  id: string;
  nickname: string;
  superuser: boolean;
};

export type UserResponse = {
  country?: string;
  distance_unit?: string;
  id: string;
  nickname: string;
  temp_unit?: string;
  updated_privacy_policy?: PrivacyPolicyRevisionOutline | null;
};

export type ValueUpdatedAtEvccAutoRecoveringValueUnion = {
  updated_at: Time;
  value: EvccAutoRecoveringValueUnion;
};

export type ValueUpdatedAtEvccRelayState = {
  updated_at: Time;
  value: string;
};

export type ValueUpdatedAtEvccSelfTestValueUnion = {
  updated_at: Time;
  value: EvccSelfTestValueUnion;
};

export type ValueUpdatedAtBool = {
  updated_at: Time;
  value: boolean;
};

export type Vehicle = {
  detail: VehicleDetail;
  manufacturer: string;
};

export type VehicleBodyColor =
  | "black"
  | "grey"
  | "white"
  | "red"
  | "blue"
  | "light_blue"
  | "green"
  | "beige";

export type VehicleBodyType =
  | "kei"
  | "compact"
  | "hatchback"
  | "minivan"
  | "sedan"
  | "suv"
  | "coupe";

export type VehicleDetail = {
  battery_capacity?: number | null;
  body_color: VehicleBodyColor;
  body_type: VehicleBodyType;
  model?: string | null;
  model_year?: number | null;
};

export type Post1ApplianceOrdersData = {
  /**
   * ReorderAppliancesParams
   */
  body: ReorderAppliancesParams;
  path?: never;
  query?: never;
  url: "/1/appliance_orders";
};

export type Post1ApplianceOrdersResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1ApplianceOrdersResponse =
  Post1ApplianceOrdersResponses[keyof Post1ApplianceOrdersResponses];

export type Get1AppliancesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/1/appliances";
};

export type Get1AppliancesResponses = {
  /**
   * ApplianceResponses
   */
  200: ApplianceResponses;
};

export type Get1AppliancesResponse = Get1AppliancesResponses[keyof Get1AppliancesResponses];

export type Post1AppliancesData = {
  /**
   * CreateApplianceRequest
   */
  body: CreateApplianceRequest;
  path?: never;
  query?: never;
  url: "/1/appliances";
};

export type Post1AppliancesResponses = {
  /**
   * ApplianceResponse
   */
  200: ApplianceResponse;
};

export type Post1AppliancesResponse = Post1AppliancesResponses[keyof Post1AppliancesResponses];

export type Post1AppliancesByApplianceidData = {
  /**
   * UpdateRequest
   */
  body: AppliancesUpdateRequest;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}";
};

export type Post1AppliancesByApplianceidResponses = {
  /**
   * ApplianceResponse
   */
  200: ApplianceResponse;
};

export type Post1AppliancesByApplianceidResponse =
  Post1AppliancesByApplianceidResponses[keyof Post1AppliancesByApplianceidResponses];

export type Post1AppliancesByApplianceidAirconSettingsData = {
  /**
   * AirConParams_
   */
  body: AirConParams;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/aircon_settings";
};

export type Post1AppliancesByApplianceidAirconSettingsResponses = {
  /**
   * AC settings.
   */
  200: AirconSettingsResponse;
};

export type Post1AppliancesByApplianceidAirconSettingsResponse =
  Post1AppliancesByApplianceidAirconSettingsResponses[keyof Post1AppliancesByApplianceidAirconSettingsResponses];

export type Post1AppliancesByApplianceidDeleteData = {
  /**
   * EmptyObject
   */
  body: EmptyObject;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/delete";
};

export type Post1AppliancesByApplianceidDeleteResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1AppliancesByApplianceidDeleteResponse =
  Post1AppliancesByApplianceidDeleteResponses[keyof Post1AppliancesByApplianceidDeleteResponses];

export type Post1AppliancesByApplianceidFloorHeaterSettingsData = {
  /**
   * AirConParams_
   */
  body: AirConParams;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/floor_heater_settings";
};

export type Post1AppliancesByApplianceidFloorHeaterSettingsResponses = {
  /**
   * ApplianceResponse
   */
  200: ApplianceResponse;
};

export type Post1AppliancesByApplianceidFloorHeaterSettingsResponse =
  Post1AppliancesByApplianceidFloorHeaterSettingsResponses[keyof Post1AppliancesByApplianceidFloorHeaterSettingsResponses];

export type Post1AppliancesByApplianceidLightData = {
  /**
   * Light parameters.
   */
  body: LightParams;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/light";
};

export type Post1AppliancesByApplianceidLightResponses = {
  /**
   * Light state.
   */
  200: LightState;
};

export type Post1AppliancesByApplianceidLightResponse =
  Post1AppliancesByApplianceidLightResponses[keyof Post1AppliancesByApplianceidLightResponses];

export type Post1AppliancesByApplianceidLightProjectorData = {
  /**
   * LightProjector parameters.
   */
  body: LightProjectorParams;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/light_projector";
};

export type Post1AppliancesByApplianceidLightProjectorResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1AppliancesByApplianceidLightProjectorResponse =
  Post1AppliancesByApplianceidLightProjectorResponses[keyof Post1AppliancesByApplianceidLightProjectorResponses];

export type Get1AppliancesByApplianceidPowerDistBoardData = {
  body?: never;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/power_dist_board";
};

export type Get1AppliancesByApplianceidPowerDistBoardResponses = {
  /**
   * Power distribution board dashboard
   */
  200: PowerdistboardDashboard;
};

export type Get1AppliancesByApplianceidPowerDistBoardResponse =
  Get1AppliancesByApplianceidPowerDistBoardResponses[keyof Get1AppliancesByApplianceidPowerDistBoardResponses];

export type Post1AppliancesByApplianceidPowerDistBoardChannelData = {
  /**
   * Channel
   */
  body: PowerdistboardChannel;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/power_dist_board/channel";
};

export type Post1AppliancesByApplianceidPowerDistBoardChannelResponses = {
  /**
   * Channel
   */
  200: PowerdistboardChannel;
};

export type Post1AppliancesByApplianceidPowerDistBoardChannelResponse =
  Post1AppliancesByApplianceidPowerDistBoardChannelResponses[keyof Post1AppliancesByApplianceidPowerDistBoardChannelResponses];

export type Post1AppliancesByApplianceidSesameBotClickData = {
  body?: never;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/sesame_bot/click";
};

export type Post1AppliancesByApplianceidSesameBotClickResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1AppliancesByApplianceidSesameBotClickResponse =
  Post1AppliancesByApplianceidSesameBotClickResponses[keyof Post1AppliancesByApplianceidSesameBotClickResponses];

export type Post1AppliancesByApplianceidSignalOrdersData = {
  /**
   * ReorderSignalsParams
   */
  body: ReorderSignalsParams;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/signal_orders";
};

export type Post1AppliancesByApplianceidSignalOrdersResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1AppliancesByApplianceidSignalOrdersResponse =
  Post1AppliancesByApplianceidSignalOrdersResponses[keyof Post1AppliancesByApplianceidSignalOrdersResponses];

export type Get1AppliancesByApplianceidSignalsData = {
  body?: never;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/signals";
};

export type Get1AppliancesByApplianceidSignalsResponses = {
  /**
   * Signals
   */
  200: Signals;
};

export type Get1AppliancesByApplianceidSignalsResponse =
  Get1AppliancesByApplianceidSignalsResponses[keyof Get1AppliancesByApplianceidSignalsResponses];

export type Post1AppliancesByApplianceidSignalsData = {
  /**
   * Signal parameters.
   */
  body: CreateSignalParameters;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/signals";
};

export type Post1AppliancesByApplianceidSignalsResponses = {
  /**
   * Signal
   */
  200: Signal;
};

export type Post1AppliancesByApplianceidSignalsResponse =
  Post1AppliancesByApplianceidSignalsResponses[keyof Post1AppliancesByApplianceidSignalsResponses];

export type Post1AppliancesByApplianceidTvData = {
  /**
   * TV parameters.
   */
  body: TvParams;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/appliances/{applianceid}/tv";
};

export type Post1AppliancesByApplianceidTvResponses = {
  /**
   * TV state.
   */
  200: TvState;
};

export type Post1AppliancesByApplianceidTvResponse =
  Post1AppliancesByApplianceidTvResponses[keyof Post1AppliancesByApplianceidTvResponses];

export type Get1BleAppliancesByApplianceidPrivateMacrosData = {
  body?: never;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/ble/appliances/{applianceid}/private_macros";
};

export type Get1BleAppliancesByApplianceidPrivateMacrosResponses = {
  /**
   * BLEPrivateMacroResponses
   */
  200: BlePrivateMacroResponses;
};

export type Get1BleAppliancesByApplianceidPrivateMacrosResponse =
  Get1BleAppliancesByApplianceidPrivateMacrosResponses[keyof Get1BleAppliancesByApplianceidPrivateMacrosResponses];

export type Post1BlePrivateMacrosByPrivatemacroidExecData = {
  body?: never;
  path: {
    /**
     * BLE Private Macro ID
     */
    privatemacroid: string;
  };
  query?: never;
  url: "/1/ble/private_macros/{privatemacroid}/exec";
};

export type Post1BlePrivateMacrosByPrivatemacroidExecResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1BlePrivateMacrosByPrivatemacroidExecResponse =
  Post1BlePrivateMacrosByPrivatemacroidExecResponses[keyof Post1BlePrivateMacrosByPrivatemacroidExecResponses];

export type Post1DetectapplianceData = {
  /**
   * DetectApplianceRequest
   */
  body: DetectApplianceRequest;
  path?: never;
  query?: never;
  url: "/1/detectappliance";
};

export type Post1DetectapplianceResponses = {
  /**
   * List of air conditioner model and settings. Best match comes first.
   */
  200: ApplianceModelAndParams;
};

export type Post1DetectapplianceResponse =
  Post1DetectapplianceResponses[keyof Post1DetectapplianceResponses];

export type Get1DevicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/1/devices";
};

export type Get1DevicesResponses = {
  /**
   * DeviceResponses
   */
  200: DeviceResponses;
};

export type Get1DevicesResponse = Get1DevicesResponses[keyof Get1DevicesResponses];

export type Post1DevicesByDeviceidData = {
  /**
   * UpdateRequest
   */
  body: DevicesUpdateRequest;
  path: {
    /**
     * Device Id
     */
    deviceid: string;
  };
  query?: never;
  url: "/1/devices/{deviceid}";
};

export type Post1DevicesByDeviceidResponses = {
  /**
   * Device
   */
  200: Device;
};

export type Post1DevicesByDeviceidResponse =
  Post1DevicesByDeviceidResponses[keyof Post1DevicesByDeviceidResponses];

export type Get1DevicesByDeviceidAppliancesData = {
  body?: never;
  path: {
    /**
     * Device Id
     */
    deviceid: string;
  };
  query?: never;
  url: "/1/devices/{deviceid}/appliances";
};

export type Get1DevicesByDeviceidAppliancesResponses = {
  /**
   * ApplianceResponses
   */
  200: ApplianceResponses;
};

export type Get1DevicesByDeviceidAppliancesResponse =
  Get1DevicesByDeviceidAppliancesResponses[keyof Get1DevicesByDeviceidAppliancesResponses];

export type Post1DevicesByDeviceidDeleteData = {
  /**
   * DeleteRequest
   */
  body: DevicesDeleteRequest;
  path: {
    /**
     * Device Id
     */
    deviceid: string;
  };
  query?: never;
  url: "/1/devices/{deviceid}/delete";
};

export type Post1DevicesByDeviceidDeleteResponses = {
  /**
   * DeleteResponse
   */
  200: DevicesDeleteResponse;
};

export type Post1DevicesByDeviceidDeleteResponse =
  Post1DevicesByDeviceidDeleteResponses[keyof Post1DevicesByDeviceidDeleteResponses];

export type Get1DevicesByDeviceidElectricityTimeSeriesHourlyData = {
  body?: never;
  path: {
    /**
     * Device Id
     */
    deviceid: string;
  };
  query?: never;
  url: "/1/devices/{deviceid}/electricity/time_series/hourly";
};

export type Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses = {
  /**
   * DeviceEnergyTimeSeries
   */
  200: DeviceEnergyTimeSeries;
};

export type Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponse =
  Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses[keyof Get1DevicesByDeviceidElectricityTimeSeriesHourlyResponses];

export type Post1DevicesByDeviceidHumidityOffsetData = {
  /**
   * Humidity offset parameters.
   */
  body: HumidityOffsetParams;
  path: {
    /**
     * Device Id
     */
    deviceid: string;
  };
  query?: never;
  url: "/1/devices/{deviceid}/humidity_offset";
};

export type Post1DevicesByDeviceidHumidityOffsetResponses = {
  /**
   * DeviceResponse
   */
  200: DeviceResponse;
};

export type Post1DevicesByDeviceidHumidityOffsetResponse =
  Post1DevicesByDeviceidHumidityOffsetResponses[keyof Post1DevicesByDeviceidHumidityOffsetResponses];

export type Post1DevicesByDeviceidTemperatureOffsetData = {
  /**
   * Temperature offset parameters.
   */
  body: TemperatureOffsetParams;
  path: {
    /**
     * Device Id
     */
    deviceid: string;
  };
  query?: never;
  url: "/1/devices/{deviceid}/temperature_offset";
};

export type Post1DevicesByDeviceidTemperatureOffsetResponses = {
  /**
   * DeviceResponse
   */
  200: DeviceResponse;
};

export type Post1DevicesByDeviceidTemperatureOffsetResponse =
  Post1DevicesByDeviceidTemperatureOffsetResponses[keyof Post1DevicesByDeviceidTemperatureOffsetResponses];

export type Get1EchonetliteAppliancesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/1/echonetlite/appliances";
};

export type Get1EchonetliteAppliancesResponses = {
  /**
   * EchonetLiteApplianceResponse
   */
  200: EchonetLiteApplianceResponse;
};

export type Get1EchonetliteAppliancesResponse =
  Get1EchonetliteAppliancesResponses[keyof Get1EchonetliteAppliancesResponses];

export type Post1EchonetliteAppliancesByApplianceidRefreshData = {
  /**
   * RefreshELPropertyRequest
   */
  body: RefreshElPropertyRequest;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/echonetlite/appliances/{applianceid}/refresh";
};

export type Post1EchonetliteAppliancesByApplianceidRefreshResponses = {
  /**
   * EmptyObject
   */
  202: EmptyObject;
};

export type Post1EchonetliteAppliancesByApplianceidRefreshResponse =
  Post1EchonetliteAppliancesByApplianceidRefreshResponses[keyof Post1EchonetliteAppliancesByApplianceidRefreshResponses];

export type Post1EchonetliteAppliancesByApplianceidSetData = {
  /**
   * SetELPropertyRequest
   */
  body: SetElPropertyRequest;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/echonetlite/appliances/{applianceid}/set";
};

export type Post1EchonetliteAppliancesByApplianceidSetResponses = {
  /**
   * EmptyObject
   */
  202: EmptyObject;
};

export type Post1EchonetliteAppliancesByApplianceidSetResponse =
  Post1EchonetliteAppliancesByApplianceidSetResponses[keyof Post1EchonetliteAppliancesByApplianceidSetResponses];

export type Post1EvccAppliancesByApplianceidStateData = {
  /**
   * UpdateEVCCStateRequest
   */
  body: UpdateEvccStateRequest;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/1/evcc/appliances/{applianceid}/state";
};

export type Post1EvccAppliancesByApplianceidStateResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1EvccAppliancesByApplianceidStateResponse =
  Post1EvccAppliancesByApplianceidStateResponses[keyof Post1EvccAppliancesByApplianceidStateResponses];

export type Get1HomesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/1/homes";
};

export type Get1HomesResponses = {
  /**
   * HomeResponses
   */
  200: HomeResponses;
};

export type Get1HomesResponse = Get1HomesResponses[keyof Get1HomesResponses];

export type Post1HomesData = {
  /**
   * HomeParams
   */
  body: HomeParams;
  path?: never;
  query?: never;
  url: "/1/homes";
};

export type Post1HomesResponses = {
  /**
   * HomeResponse
   */
  200: HomeResponse;
};

export type Post1HomesResponse = Post1HomesResponses[keyof Post1HomesResponses];

export type Post1HomesByHomeidData = {
  /**
   * HomeParams
   */
  body: HomeParams;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}";
};

export type Post1HomesByHomeidResponses = {
  /**
   * HomeResponse
   */
  200: HomeResponse;
};

export type Post1HomesByHomeidResponse =
  Post1HomesByHomeidResponses[keyof Post1HomesByHomeidResponses];

export type Post1HomesByHomeidDeleteData = {
  body?: never;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/delete";
};

export type Post1HomesByHomeidDeleteResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1HomesByHomeidDeleteResponse =
  Post1HomesByHomeidDeleteResponses[keyof Post1HomesByHomeidDeleteResponses];

export type Get1HomesByHomeidDevicesData = {
  body?: never;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/devices";
};

export type Get1HomesByHomeidDevicesResponses = {
  /**
   * DeviceResponses
   */
  200: DeviceResponses;
};

export type Get1HomesByHomeidDevicesResponse =
  Get1HomesByHomeidDevicesResponses[keyof Get1HomesByHomeidDevicesResponses];

export type Post1HomesByHomeidInvitesData = {
  body?: never;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/invites";
};

export type Post1HomesByHomeidInvitesResponses = {
  /**
   * HomeInvite
   */
  200: HomeInvite;
};

export type Post1HomesByHomeidInvitesResponse =
  Post1HomesByHomeidInvitesResponses[keyof Post1HomesByHomeidInvitesResponses];

export type Post1HomesByHomeidKickData = {
  /**
   * HomeUserParams
   */
  body: HomeUserParams;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/kick";
};

export type Post1HomesByHomeidKickResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1HomesByHomeidKickResponse =
  Post1HomesByHomeidKickResponses[keyof Post1HomesByHomeidKickResponses];

export type Post1HomesByHomeidLocationData = {
  body?: never;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/location";
};

export type Post1HomesByHomeidLocationResponses = {
  /**
   * HomeResponse
   */
  200: HomeResponse;
};

export type Post1HomesByHomeidLocationResponse =
  Post1HomesByHomeidLocationResponses[keyof Post1HomesByHomeidLocationResponses];

export type Post1HomesByHomeidLocationDeleteData = {
  /**
   * DeleteLocationRequest
   */
  body: HomesDeleteLocationRequest;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/location/delete";
};

export type Post1HomesByHomeidLocationDeleteResponses = {
  /**
   * DeleteLocationResponse
   */
  200: HomesDeleteLocationResponse;
};

export type Post1HomesByHomeidLocationDeleteResponse =
  Post1HomesByHomeidLocationDeleteResponses[keyof Post1HomesByHomeidLocationDeleteResponses];

export type Post1HomesByHomeidLocationStateUpdateData = {
  body?: never;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/location_state/update";
};

export type Post1HomesByHomeidLocationStateUpdateResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1HomesByHomeidLocationStateUpdateResponse =
  Post1HomesByHomeidLocationStateUpdateResponses[keyof Post1HomesByHomeidLocationStateUpdateResponses];

export type Post1HomesByHomeidOwnerData = {
  /**
   * HomeUserParams
   */
  body: HomeUserParams;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/owner";
};

export type Post1HomesByHomeidOwnerResponses = {
  /**
   * HomeResponse
   */
  200: HomeResponse;
};

export type Post1HomesByHomeidOwnerResponse =
  Post1HomesByHomeidOwnerResponses[keyof Post1HomesByHomeidOwnerResponses];

export type Post1HomesByHomeidPartData = {
  body?: never;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/part";
};

export type Post1HomesByHomeidPartResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1HomesByHomeidPartResponse =
  Post1HomesByHomeidPartResponses[keyof Post1HomesByHomeidPartResponses];

export type Post1HomesByHomeidTransferByTohomeidData = {
  /**
   * TransferRequest
   */
  body: TransferRequest;
  path: {
    /**
     * Home Id
     */
    homeid: string;
    /**
     * Transfer to Home Id
     */
    tohomeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/transfer/{tohomeid}";
};

export type Post1HomesByHomeidTransferByTohomeidResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1HomesByHomeidTransferByTohomeidResponse =
  Post1HomesByHomeidTransferByTohomeidResponses[keyof Post1HomesByHomeidTransferByTohomeidResponses];

export type Get1HomesByHomeidUsersData = {
  body?: never;
  path: {
    /**
     * Home Id
     */
    homeid: string;
  };
  query?: never;
  url: "/1/homes/{homeid}/users";
};

export type Get1HomesByHomeidUsersResponses = {
  /**
   * UserAndRoles
   */
  200: UserAndRoles;
};

export type Get1HomesByHomeidUsersResponse =
  Get1HomesByHomeidUsersResponses[keyof Get1HomesByHomeidUsersResponses];

export type Get1InvitesByInvitetokenData = {
  body?: never;
  path: {
    /**
     * Invite Token
     */
    invitetoken: string;
  };
  query?: never;
  url: "/1/invites/{invitetoken}";
};

export type Get1InvitesByInvitetokenResponses = {
  /**
   * HomeInvite
   */
  200: HomeInvite;
};

export type Get1InvitesByInvitetokenResponse =
  Get1InvitesByInvitetokenResponses[keyof Get1InvitesByInvitetokenResponses];

export type Post1InvitesByInvitetokenData = {
  body?: never;
  path: {
    /**
     * Invite Token
     */
    invitetoken: string;
  };
  query?: never;
  url: "/1/invites/{invitetoken}";
};

export type Post1InvitesByInvitetokenResponses = {
  /**
   * HomeResponse
   */
  200: HomeResponse;
};

export type Post1InvitesByInvitetokenResponse =
  Post1InvitesByInvitetokenResponses[keyof Post1InvitesByInvitetokenResponses];

export type Post1SignalsBySignalidData = {
  /**
   * Signal parameters.
   */
  body: UpdateSignalParameters;
  path: {
    /**
     * Signal Id
     */
    signalid: string;
  };
  query?: never;
  url: "/1/signals/{signalid}";
};

export type Post1SignalsBySignalidResponses = {
  /**
   * Signal
   */
  200: Signal;
};

export type Post1SignalsBySignalidResponse =
  Post1SignalsBySignalidResponses[keyof Post1SignalsBySignalidResponses];

export type Post1SignalsBySignalidDeleteData = {
  /**
   * EmptyObject
   */
  body: EmptyObject;
  path: {
    /**
     * Signal Id
     */
    signalid: string;
  };
  query?: never;
  url: "/1/signals/{signalid}/delete";
};

export type Post1SignalsBySignalidDeleteResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1SignalsBySignalidDeleteResponse =
  Post1SignalsBySignalidDeleteResponses[keyof Post1SignalsBySignalidDeleteResponses];

export type Post1SignalsBySignalidSendData = {
  /**
   * EmptyObject
   */
  body: EmptyObject;
  path: {
    /**
     * Signal Id
     */
    signalid: string;
  };
  query?: never;
  url: "/1/signals/{signalid}/send";
};

export type Post1SignalsBySignalidSendResponses = {
  /**
   * EmptyObject
   */
  200: EmptyObject;
};

export type Post1SignalsBySignalidSendResponse =
  Post1SignalsBySignalidSendResponses[keyof Post1SignalsBySignalidSendResponses];

export type Get1UsersMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/1/users/me";
};

export type Get1UsersMeResponses = {
  /**
   * User information.
   */
  200: UserResponse;
};

export type Get1UsersMeResponse = Get1UsersMeResponses[keyof Get1UsersMeResponses];

export type Post1UsersMeData = {
  /**
   * UpdateProfileParam
   */
  body: UpdateProfileParam;
  path?: never;
  query?: never;
  url: "/1/users/me";
};

export type Post1UsersMeResponses = {
  /**
   * User information.
   */
  200: UserResponse;
};

export type Post1UsersMeResponse = Post1UsersMeResponses[keyof Post1UsersMeResponses];

export type Post2AppliancesByApplianceidAirconSettingsData = {
  /**
   * AirConParams_
   */
  body: AirConParams;
  path: {
    /**
     * Appliance Id
     */
    applianceid: string;
  };
  query?: never;
  url: "/2/appliances/{applianceid}/aircon_settings";
};

export type Post2AppliancesByApplianceidAirconSettingsResponses = {
  /**
   * ApplianceResponse
   */
  200: ApplianceResponse;
};

export type Post2AppliancesByApplianceidAirconSettingsResponse =
  Post2AppliancesByApplianceidAirconSettingsResponses[keyof Post2AppliancesByApplianceidAirconSettingsResponses];

export type Post2DetectapplianceData = {
  /**
   * DetectApplianceV2Request
   */
  body: AppliancesDetectApplianceV2Request;
  path?: never;
  query?: never;
  url: "/2/detectappliance";
};

export type Post2DetectapplianceResponses = {
  /**
   * DetectApplianceV2Response
   */
  200: AppliancesDetectApplianceV2Response;
};

export type Post2DetectapplianceResponse =
  Post2DetectapplianceResponses[keyof Post2DetectapplianceResponses];
