// This file is auto-generated by @hey-api/openapi-ts

import * as v from "valibot";

export const vAddr = v.string();

export const vAirConParams = v.object({
  air_direction: v.string(),
  air_direction_h: v.string(),
  air_volume: v.string(),
  button: v.string(),
  extra: v.nullish(v.record(v.string(), v.string())),
  operation_mode: v.string(),
  temperature: v.string(),
  temperature_unit: v.string(),
});

export const vAirDirectionHRange = v.nullable(v.array(v.string()));

export const vAirDirectionRange = v.nullable(v.array(v.string()));

export const vAirVolumeRange = v.nullable(v.array(v.string()));

export const vApplianceElModel = v.object({
  id: v.string(),
  image: v.string(),
  manufacturer: v.string(),
  name: v.string(),
});

export const vApplianceFloorHeaterModel = v.object({
  country: v.string(),
  id: v.string(),
  image: v.string(),
  manufacturer: v.string(),
  name: v.string(),
  remote_name: v.string(),
  series: v.string(),
});

export const vApplianceLightModel = v.object({
  country: v.string(),
  id: v.string(),
  image: v.string(),
  manufacturer: v.string(),
  name: v.string(),
  remote_name: v.string(),
});

export const vApplianceLightProjectorModel = v.object({
  country: v.string(),
  id: v.string(),
  image: v.string(),
  manufacturer: v.string(),
  name: v.string(),
  remote_name: v.string(),
});

export const vApplianceModel = v.object({
  country: v.string(),
  id: v.string(),
  image: v.string(),
  manufacturer: v.string(),
  name: v.string(),
  remote_name: v.string(),
  series: v.string(),
});

export const vApplianceTvModel = v.object({
  country: v.string(),
  id: v.string(),
  image: v.string(),
  manufacturer: v.string(),
  name: v.string(),
  remote_name: v.string(),
});

export const vAppliancesDetectApplianceV2Request = v.object({
  Device: v.nullish(v.string()),
  Message: v.string(),
  SessionToken: v.string(),
});

export const vAppliancesUpdateRequest = v.object({
  image: v.string(),
  nickname: v.string(),
});

export const vArea = v.picklist([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);

export const vBleHueLightControlItem = v.object({
  light_type: v.string(),
});

export const vBleModel = v.object({
  id: v.string(),
  image: v.string(),
  name: v.string(),
  slug: v.string(),
});

export const vApplianceModelUnion = v.nullable(
  v.union([
    vApplianceModel,
    vApplianceTvModel,
    vApplianceLightModel,
    vApplianceElModel,
    vApplianceLightProjectorModel,
    vApplianceFloorHeaterModel,
    vBleModel,
  ]),
);

export const vBlePrivateMacroResponse = v.object({
  id: v.string(),
  url: v.string(),
});

export const vBlePrivateMacroResponses = v.nullable(v.array(vBlePrivateMacroResponse));

export const vBleSesameControlItem = v.object({
  device_type: v.string(),
  key_level: v.string(),
  user_index: v.nullable(v.array(v.pipe(v.number(), v.integer()))),
  uuid: v.string(),
});

export const vBleControlItem = v.object({
  addr: v.string(),
  addr_type: v.string(),
  bonded: v.boolean(),
  hue: v.nullish(vBleHueLightControlItem),
  macros: v.nullish(v.object({})),
  sesame: v.nullish(vBleSesameControlItem),
});

export const vButtonDbButton = v.object({
  image: v.string(),
  label: v.string(),
  name: v.string(),
});

export const vCampaignSlug = v.string();

export const vAirconSemResponse = v.object({
  adjusting: v.boolean(),
  area: vArea,
  campaign_slug: vCampaignSlug,
  enabled: v.boolean(),
});

/**
 * Breaker capacity in amperes (A). Must be between 10 and 200.
 */
export const vCoreHomeBreakerCapacity = v.pipe(
  v.number(),
  v.integer(),
  v.minValue(10),
  v.maxValue(200),
);

/**
 * Serial number of the device.
 */
export const vCoreSerialNumber = v.string();

export const vCreateApplianceRequest = v.object({
  device: v.string(),
  image: v.string(),
  model: v.string(),
  model_type: v.string(),
  nickname: v.string(),
});

export const vCreateSignalParameters = v.object({
  image: v.string(),
  message: v.string(),
  name: v.string(),
});

export const vDetectApplianceRequest = v.object({
  Device: v.nullish(v.string()),
  Message: v.string(),
});

export const vDeviceCommissioneeFabricResponse = v.object({
  cfabric: v.string(),
  company_name: v.string(),
  label: v.string(),
  vendor_name: v.string(),
});

export const vDevicesDeleteRequest = v.record(v.string(), v.unknown());

export const vDevicesDeleteResponse = v.record(v.string(), v.unknown());

export const vDevicesUpdateRequest = v.object({
  name: v.string(),
});

export const vElManufacturer = v.object({
  code: v.string(),
  name: v.string(),
});

export const vElResponse = v.object({
  identifier: v.string(),
  instance: v.string(),
  ip: v.nullish(v.string()),
  manufacturer: vElManufacturer,
  route_type: v.string(),
  version: v.string(),
});

export const vEvccStateErrorValueAbnormalTemperature = v.strictObject({
  kind: v.picklist(["abnormal_temperature"]),
  type: v.picklist(["over_temperature", "unknown"]),
});

export const vEvccStateErrorValueMemory = v.strictObject({
  kind: v.picklist(["memory"]),
  type: v.picklist([
    "read_status_error",
    "write_status_error",
    "read_energy_error",
    "write_energy_error",
    "unknown",
  ]),
});

export const vEvccStateErrorValueMeter = v.strictObject({
  kind: v.picklist(["meter"]),
  type: v.picklist(["overvoltage", "undervoltage", "overcurrent", "energy_leak", "unknown"]),
});

export const vEvccStateErrorValueMeterCommunication = v.strictObject({
  kind: v.picklist(["meter_communication"]),
  type: v.picklist(["serial_error", "unknown"]),
});

export const vEvccStateErrorValueRelay = v.strictObject({
  kind: v.picklist(["relay"]),
  type: v.picklist(["conflict", "unknown"]),
});

export const vEvccStateErrorValueUnrecoverable = v.strictObject({
  kind: v.picklist(["unrecoverable"]),
  type: v.picklist([
    "boot_error",
    "self_test_under_fatal_error_failed",
    "emergency_stop_from_server",
    "unknown",
  ]),
});

export const vEvccSelfTestValueUnion = v.union([
  v.intersect([
    v.object({
      kind: v.literal("relay"),
    }),
    vEvccStateErrorValueRelay,
  ]),
  v.intersect([
    v.object({
      kind: v.literal("meter"),
    }),
    vEvccStateErrorValueMeter,
  ]),
  v.intersect([
    v.object({
      kind: v.literal("meter_communication"),
    }),
    vEvccStateErrorValueMeterCommunication,
  ]),
  v.intersect([
    v.object({
      kind: v.literal("memory"),
    }),
    vEvccStateErrorValueMemory,
  ]),
  v.intersect([
    v.object({
      kind: v.literal("unrecoverable"),
    }),
    vEvccStateErrorValueUnrecoverable,
  ]),
]);

export const vEvccStateErrorValueWarnings = v.strictObject({
  kind: v.picklist(["warnings"]),
  type: v.picklist(["over_current_warning", "unknown"]),
});

export const vEvccAutoRecoveringValueUnion = v.union([
  v.intersect([
    v.object({
      kind: v.literal("abnormal_temperature"),
    }),
    vEvccStateErrorValueAbnormalTemperature,
  ]),
  v.intersect([
    v.object({
      kind: v.literal("warnings"),
    }),
    vEvccStateErrorValueWarnings,
  ]),
]);

export const vEmptyObject = v.record(v.string(), v.unknown());

export const vExtraOptionText = v.string();

export const vExtraOption = v.object({
  default: v.optional(v.boolean()),
  text: vExtraOptionText,
  value: v.string(),
});

export const vAirConExtraResponse = v.object({
  availability: v.string(),
  defaultTime: v.optional(v.string()),
  description: v.string(),
  id: v.string(),
  options: v.nullish(v.array(vExtraOption)),
  text: v.string(),
  type: v.string(),
});

export const vHexBytes = v.nullable(v.array(v.pipe(v.number(), v.integer())));

export const vHome = v.object({
  breaker_capacity: v.nullish(vCoreHomeBreakerCapacity),
  id: v.string(),
  name: v.string(),
});

export const vHomeParams = v.object({
  name: v.string(),
});

export const vHomeUserParams = v.object({
  user: v.string(),
});

export const vHomesDeleteLocationRequest = v.record(v.string(), v.unknown());

export const vHumidityOffsetParams = v.object({
  offset: v.number(),
});

export const vLightParams = v.object({
  button: v.string(),
});

export const vLightProjectorParams = v.object({
  button: v.string(),
});

export const vLightState = v.object({
  brightness: v.string(),
  last_button: v.string(),
  power: v.string(),
});

export const vLightResponse = v.object({
  buttons: v.nullable(v.array(vButtonDbButton)),
  state: v.nullish(vLightState),
});

export const vLinkText = v.object({
  link: v.string(),
  text: v.string(),
});

/**
 * Time series of metrics. Each element is a 2-element tuple [unix time in seconds, value in kWh]. e.g. [1700000000, 1.234]
 */
export const vMetrics = v.array(v.tuple([v.number(), v.number()]));

export const vDeviceEnergyTimeSeries = v.object({
  from_evcd: v.optional(vMetrics),
  from_fuel_cell: v.optional(vMetrics),
  from_grid: v.optional(vMetrics),
  from_solar_power: v.optional(vMetrics),
  from_storage_battery: v.optional(vMetrics),
  home_consumed: v.optional(vMetrics),
  to_evcc: v.optional(vMetrics),
  to_evcd: v.optional(vMetrics),
  to_grid: v.optional(vMetrics),
  to_storage_battery: v.optional(vMetrics),
});

export const vMorninPlusDeviceResponse = v.object({
  active: v.boolean(),
  id: v.string(),
  image: v.string(),
  name: v.string(),
});

export const vMorninPlusResponse = v.object({
  devices: v.nullable(v.array(v.nullable(vMorninPlusDeviceResponse))),
  hi_speed_mode: v.boolean(),
});

export const vParams = v.object({
  button: v.string(),
  dir: v.string(),
  dirh: v.string(),
  extra: v.nullish(v.record(v.string(), v.string())),
  mode: v.string(),
  temp: v.string(),
  temp_unit: v.string(),
  vol: v.string(),
});

export const vApplianceModelAndParam = v.object({
  model: vApplianceModel,
  params: vParams,
});

export const vApplianceModelAndParams = v.nullable(v.array(vApplianceModelAndParam));

export const vAppliancesDetectApplianceV2Response = v.object({
  results: v.nullable(v.array(vApplianceModelAndParam)),
  session_token: v.string(),
  suggested_action: v.string(),
  suggested_action_message: v.string(),
});

export const vPowerdistboardChannel = v.object({
  appliance_name: v.string(),
  number: v.pipe(v.number(), v.integer()),
  room_name: v.string(),
});

export const vPowerdistboardBoard = v.object({
  channels: v.nullable(v.array(vPowerdistboardChannel)),
});

export const vPowerdistboardOptions = v.object({
  appliance_names: v.nullable(v.array(v.string())),
  room_names: v.nullable(v.array(v.string())),
});

export const vPowerdistboardDashboard = v.object({
  options: vPowerdistboardOptions,
  power_dist_board: vPowerdistboardBoard,
});

export const vPrivacyPolicyRevisionOutline = v.object({
  body: v.string(),
  links: v.nullable(v.object({})),
  title: v.string(),
});

export const vQrioLockDeviceResponse = v.object({
  id: v.pipe(v.number(), v.integer()),
  image: v.string(),
  name: v.string(),
});

export const vQrioLockResponse = v.object({
  bd_address: v.string(),
  device: vQrioLockDeviceResponse,
  is_available: v.boolean(),
  sub_bd_address: v.optional(v.string()),
});

export const vRangeResponseMode = v.object({
  dir: v.nullable(v.array(v.string())),
  dirh: v.nullable(v.array(v.string())),
  temp: v.nullable(v.array(v.string())),
  vol: v.nullable(v.array(v.string())),
});

export const vAirConRangeResponse = v.object({
  extras: v.nullish(v.array(vAirConExtraResponse)),
  fixedButtons: v.nullable(v.array(v.string())),
  modes: v.nullable(v.object({})),
});

export const vAirConResponse = v.object({
  range: vAirConRangeResponse,
  tempUnit: v.string(),
});

export const vFloorHeaterResponse = v.object({
  range: vAirConRangeResponse,
  tempUnit: v.string(),
});

export const vRefreshElPropertyRequest = v.object({
  epc: v.string(),
});

export const vReorderAppliancesParams = v.object({
  appliances: v.string(),
});

export const vReorderSignalsParams = v.object({
  signals: v.string(),
});

export const vSetElPropertyRequest = v.object({
  epc: v.string(),
  val: v.string(),
});

export const vSignal = v.object({
  id: v.string(),
  image: v.string(),
  name: v.string(),
});

export const vSignals = v.nullable(v.array(vSignal));

export const vTvParams = v.object({
  button: v.string(),
});

export const vTvState = v.object({
  input: v.string(),
});

export const vTemperatureOffsetParams = v.object({
  offset: v.number(),
});

export const vTemplate: v.GenericSchema = v.object({
  image: v.string(),
  label: v.string(),
  name: v.string(),
  templates: v.nullable(v.array(v.nullable(v.lazy(() => vTemplate)))),
  text: v.string(),
  type: v.string(),
  uuid: v.string(),
  x_size: v.pipe(v.number(), v.integer()),
  y_size: v.pipe(v.number(), v.integer()),
});

export const vLightProjectordbLayout = v.object({
  image: v.string(),
  label: v.string(),
  name: v.string(),
  templates: v.nullable(v.array(v.nullable(vTemplate))),
  text: v.string(),
  type: v.string(),
  uuid: v.string(),
  x_size: v.pipe(v.number(), v.integer()),
  y_size: v.pipe(v.number(), v.integer()),
});

export const vLightProjectorResponse = v.object({
  layout: vLightProjectordbLayout,
});

export const vTime = v.pipe(v.string(), v.isoTimestamp());

export const vAirconSettingsResponse = v.object({
  button: v.string(),
  dir: v.string(),
  dirh: v.string(),
  extra: v.nullish(v.record(v.string(), v.string())),
  mode: v.string(),
  temp: v.string(),
  temp_unit: v.string(),
  updated_at: vTime,
  vol: v.string(),
});

export const vCoreSensorValue = v.object({
  created_at: vTime,
  val: v.number(),
});

export const vDevice = v.object({
  bt_mac_address: v.nullish(v.string()),
  created_at: vTime,
  firmware_version: v.string(),
  humidity_offset: v.number(),
  id: v.string(),
  mac_address: v.string(),
  name: v.string(),
  serial_number: vCoreSerialNumber,
  temperature_offset: v.number(),
  updated_at: vTime,
});

export const vElPropertyResponse = v.object({
  epc: v.pipe(v.number(), v.integer()),
  name: v.string(),
  updated_at: vTime,
  val: v.string(),
});

export const vMemberResponse = v.object({
  id: v.string(),
  joined_at: vTime,
  location_state: v.string(),
  nickname: v.string(),
  role: v.string(),
});

export const vHomeResponse = v.object({
  breaker_capacity: v.nullish(vCoreHomeBreakerCapacity),
  id: v.string(),
  name: v.string(),
  users: v.nullable(v.array(vMemberResponse)),
});

export const vHomeResponses = v.nullable(v.array(vHomeResponse));

export const vHomesDeleteLocationResponse = v.object({
  breaker_capacity: v.nullish(vCoreHomeBreakerCapacity),
  id: v.string(),
  name: v.string(),
  users: v.nullable(v.array(vMemberResponse)),
});

export const vPropertyRow = v.object({
  epc: v.string(),
  updated_at: vTime,
  val: v.string(),
});

export const vEchonetLiteAppliance = v.object({
  Device: v.nullish(vDevice),
  id: v.string(),
  nickname: v.string(),
  properties: v.nullable(v.array(vPropertyRow)),
  type: v.string(),
});

export const vEchonetLiteApplianceResponse = v.object({
  appliances: v.nullable(v.array(vEchonetLiteAppliance)),
});

export const vSmartMeterResponse = v.object({
  echonetlite_properties: v.nullable(v.array(v.nullable(vElPropertyResponse))),
});

export const vTransferRequest = v.object({
  devices: v.string(),
});

export const vTvdbRowLayout = v.object({
  buttons: v.nullable(v.array(v.string())),
  type: v.string(),
});

export const vTvResponse = v.object({
  buttons: v.nullable(v.array(vButtonDbButton)),
  layout: v.nullish(v.array(vTvdbRowLayout)),
  state: v.nullish(vTvState),
});

export const vUuid = v.string();

export const vUpdateEvccRelayState = v.picklist(["open", "close"]);

export const vUpdateEvccStateRequest = v.object({
  relay_state: vUpdateEvccRelayState,
});

export const vUpdateProfileParam = v.object({
  country: v.string(),
  distance_unit: v.string(),
  nickname: v.string(),
  temp_unit: v.string(),
});

export const vUpdateSignalParameters = v.object({
  image: v.string(),
  name: v.string(),
});

export const vUser = v.object({
  id: v.string(),
  nickname: v.string(),
});

export const vHomeInvite = v.object({
  home: v.nullish(vHome),
  url: v.string(),
  user: v.nullish(vUser),
});

export const vUserAndRole = v.object({
  role: v.string(),
  user: vUser,
});

export const vUserAndRoles = v.nullable(v.array(vUserAndRole));

export const vUserDeviceResponse = v.object({
  id: v.string(),
  nickname: v.string(),
  superuser: v.boolean(),
});

export const vDeviceResponse = v.object({
  bridged_devices_limit: v.nullish(v.pipe(v.number(), v.integer())),
  bt_mac_address: v.nullish(v.string()),
  commissionee_fabrics: v.nullish(v.array(vDeviceCommissioneeFabricResponse)),
  commissionee_fabrics_limit: v.nullish(v.pipe(v.number(), v.integer())),
  created_at: vTime,
  firmware_version: v.string(),
  humidity_offset: v.number(),
  id: v.string(),
  mac_address: v.string(),
  name: v.string(),
  newest_events: v.nullable(v.object({})),
  online: v.nullish(v.boolean()),
  serial_number: vCoreSerialNumber,
  temperature_offset: v.number(),
  updated_at: vTime,
  users: v.nullish(v.array(vUserDeviceResponse)),
});

export const vDeviceResponses = v.nullable(v.array(vDeviceResponse));

export const vUserResponse = v.object({
  country: v.optional(v.string()),
  distance_unit: v.optional(v.string()),
  id: v.string(),
  nickname: v.string(),
  temp_unit: v.optional(v.string()),
  updated_privacy_policy: v.nullish(vPrivacyPolicyRevisionOutline),
});

export const vValueUpdatedAtEvccAutoRecoveringValueUnion = v.object({
  updated_at: vTime,
  value: vEvccAutoRecoveringValueUnion,
});

export const vValueUpdatedAtEvccRelayState = v.object({
  updated_at: vTime,
  value: v.string(),
});

export const vValueUpdatedAtEvccSelfTestValueUnion = v.object({
  updated_at: vTime,
  value: vEvccSelfTestValueUnion,
});

export const vEvccStateErrorsResponse = v.object({
  auto_recovering: v.nullable(v.array(vValueUpdatedAtEvccAutoRecoveringValueUnion)),
  require_self_test: v.nullable(v.array(vValueUpdatedAtEvccSelfTestValueUnion)),
});

export const vValueUpdatedAtBool = v.object({
  updated_at: vTime,
  value: v.boolean(),
});

export const vVehicleBodyColor = v.picklist([
  "black",
  "grey",
  "white",
  "red",
  "blue",
  "light_blue",
  "green",
  "beige",
]);

export const vVehicleBodyType = v.picklist([
  "kei",
  "compact",
  "hatchback",
  "minivan",
  "sedan",
  "suv",
  "coupe",
]);

export const vVehicleDetail = v.object({
  battery_capacity: v.nullish(v.number()),
  body_color: vVehicleBodyColor,
  body_type: vVehicleBodyType,
  model: v.nullish(v.string()),
  model_year: v.nullish(v.pipe(v.number(), v.integer())),
});

export const vVehicle = v.object({
  detail: vVehicleDetail,
  manufacturer: v.string(),
});

export const vEvccResponse = v.object({
  connected_device: v.nullish(vDevice),
  current_charging_amount: v.nullish(v.number()),
  errors: v.nullish(vEvccStateErrorsResponse),
  last_operated_remotely: v.boolean(),
  online: vValueUpdatedAtBool,
  relay_state: vValueUpdatedAtEvccRelayState,
  vehicle: vVehicle,
});

export const vApplianceResponse = v.object({
  aircon: v.nullish(vAirConResponse),
  aircon_smart_eco_mode: v.nullish(vAirconSemResponse),
  ble: v.nullish(vBleControlItem),
  device: v.nullish(vDevice),
  echonetlite: v.nullish(vElResponse),
  evcc: v.nullish(vEvccResponse),
  floor_heater: v.nullish(vFloorHeaterResponse),
  id: v.string(),
  image: v.string(),
  light: v.nullish(vLightResponse),
  light_projector: v.nullish(vLightProjectorResponse),
  matter_bridged_device_state: v.nullish(v.string()),
  model: vApplianceModelUnion,
  mornin_plus: v.nullish(vMorninPlusResponse),
  nickname: v.string(),
  qrio_lock: v.nullish(vQrioLockResponse),
  settings: v.nullish(vAirconSettingsResponse),
  signals: v.nullable(v.array(vSignal)),
  smart_meter: v.nullish(vSmartMeterResponse),
  tv: v.nullish(vTvResponse),
  type: v.string(),
});

export const vApplianceResponses = v.nullable(v.array(vApplianceResponse));

/**
 * ReorderAppliancesParams
 */
export const vPost1ApplianceOrdersBody = vReorderAppliancesParams;

/**
 * EmptyObject
 */
export const vPost1ApplianceOrdersResponse = vEmptyObject;

/**
 * ApplianceResponses
 */
export const vGet1AppliancesResponse = vApplianceResponses;

/**
 * CreateApplianceRequest
 */
export const vPost1AppliancesBody = vCreateApplianceRequest;

/**
 * ApplianceResponse
 */
export const vPost1AppliancesResponse = vApplianceResponse;

/**
 * UpdateRequest
 */
export const vPost1AppliancesByApplianceidBody = vAppliancesUpdateRequest;

export const vPost1AppliancesByApplianceidPath = v.object({
  applianceid: v.string(),
});

/**
 * ApplianceResponse
 */
export const vPost1AppliancesByApplianceidResponse = vApplianceResponse;

/**
 * AirConParams_
 */
export const vPost1AppliancesByApplianceidAirconSettingsBody = vAirConParams;

export const vPost1AppliancesByApplianceidAirconSettingsPath = v.object({
  applianceid: v.string(),
});

/**
 * AC settings.
 */
export const vPost1AppliancesByApplianceidAirconSettingsResponse = vAirconSettingsResponse;

/**
 * EmptyObject
 */
export const vPost1AppliancesByApplianceidDeleteBody = vEmptyObject;

export const vPost1AppliancesByApplianceidDeletePath = v.object({
  applianceid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1AppliancesByApplianceidDeleteResponse = vEmptyObject;

/**
 * AirConParams_
 */
export const vPost1AppliancesByApplianceidFloorHeaterSettingsBody = vAirConParams;

export const vPost1AppliancesByApplianceidFloorHeaterSettingsPath = v.object({
  applianceid: v.string(),
});

/**
 * ApplianceResponse
 */
export const vPost1AppliancesByApplianceidFloorHeaterSettingsResponse = vApplianceResponse;

/**
 * Light parameters.
 */
export const vPost1AppliancesByApplianceidLightBody = vLightParams;

export const vPost1AppliancesByApplianceidLightPath = v.object({
  applianceid: v.string(),
});

/**
 * Light state.
 */
export const vPost1AppliancesByApplianceidLightResponse = vLightState;

/**
 * LightProjector parameters.
 */
export const vPost1AppliancesByApplianceidLightProjectorBody = vLightProjectorParams;

export const vPost1AppliancesByApplianceidLightProjectorPath = v.object({
  applianceid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1AppliancesByApplianceidLightProjectorResponse = vEmptyObject;

export const vGet1AppliancesByApplianceidPowerDistBoardPath = v.object({
  applianceid: v.string(),
});

/**
 * Power distribution board dashboard
 */
export const vGet1AppliancesByApplianceidPowerDistBoardResponse = vPowerdistboardDashboard;

/**
 * Channel
 */
export const vPost1AppliancesByApplianceidPowerDistBoardChannelBody = vPowerdistboardChannel;

export const vPost1AppliancesByApplianceidPowerDistBoardChannelPath = v.object({
  applianceid: v.string(),
});

/**
 * Channel
 */
export const vPost1AppliancesByApplianceidPowerDistBoardChannelResponse = vPowerdistboardChannel;

export const vPost1AppliancesByApplianceidSesameBotClickPath = v.object({
  applianceid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1AppliancesByApplianceidSesameBotClickResponse = vEmptyObject;

/**
 * ReorderSignalsParams
 */
export const vPost1AppliancesByApplianceidSignalOrdersBody = vReorderSignalsParams;

export const vPost1AppliancesByApplianceidSignalOrdersPath = v.object({
  applianceid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1AppliancesByApplianceidSignalOrdersResponse = vEmptyObject;

export const vGet1AppliancesByApplianceidSignalsPath = v.object({
  applianceid: v.string(),
});

/**
 * Signals
 */
export const vGet1AppliancesByApplianceidSignalsResponse = vSignals;

/**
 * Signal parameters.
 */
export const vPost1AppliancesByApplianceidSignalsBody = vCreateSignalParameters;

export const vPost1AppliancesByApplianceidSignalsPath = v.object({
  applianceid: v.string(),
});

/**
 * Signal
 */
export const vPost1AppliancesByApplianceidSignalsResponse = vSignal;

/**
 * TV parameters.
 */
export const vPost1AppliancesByApplianceidTvBody = vTvParams;

export const vPost1AppliancesByApplianceidTvPath = v.object({
  applianceid: v.string(),
});

/**
 * TV state.
 */
export const vPost1AppliancesByApplianceidTvResponse = vTvState;

export const vGet1BleAppliancesByApplianceidPrivateMacrosPath = v.object({
  applianceid: v.string(),
});

/**
 * BLEPrivateMacroResponses
 */
export const vGet1BleAppliancesByApplianceidPrivateMacrosResponse = vBlePrivateMacroResponses;

export const vPost1BlePrivateMacrosByPrivatemacroidExecPath = v.object({
  privatemacroid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1BlePrivateMacrosByPrivatemacroidExecResponse = vEmptyObject;

/**
 * DetectApplianceRequest
 */
export const vPost1DetectapplianceBody = vDetectApplianceRequest;

/**
 * List of air conditioner model and settings. Best match comes first.
 */
export const vPost1DetectapplianceResponse = vApplianceModelAndParams;

/**
 * DeviceResponses
 */
export const vGet1DevicesResponse = vDeviceResponses;

/**
 * UpdateRequest
 */
export const vPost1DevicesByDeviceidBody = vDevicesUpdateRequest;

export const vPost1DevicesByDeviceidPath = v.object({
  deviceid: v.string(),
});

/**
 * Device
 */
export const vPost1DevicesByDeviceidResponse = vDevice;

export const vGet1DevicesByDeviceidAppliancesPath = v.object({
  deviceid: v.string(),
});

/**
 * ApplianceResponses
 */
export const vGet1DevicesByDeviceidAppliancesResponse = vApplianceResponses;

/**
 * DeleteRequest
 */
export const vPost1DevicesByDeviceidDeleteBody = vDevicesDeleteRequest;

export const vPost1DevicesByDeviceidDeletePath = v.object({
  deviceid: v.string(),
});

/**
 * DeleteResponse
 */
export const vPost1DevicesByDeviceidDeleteResponse = vDevicesDeleteResponse;

export const vGet1DevicesByDeviceidElectricityTimeSeriesHourlyPath = v.object({
  deviceid: v.string(),
});

/**
 * DeviceEnergyTimeSeries
 */
export const vGet1DevicesByDeviceidElectricityTimeSeriesHourlyResponse = vDeviceEnergyTimeSeries;

/**
 * Humidity offset parameters.
 */
export const vPost1DevicesByDeviceidHumidityOffsetBody = vHumidityOffsetParams;

export const vPost1DevicesByDeviceidHumidityOffsetPath = v.object({
  deviceid: v.string(),
});

/**
 * DeviceResponse
 */
export const vPost1DevicesByDeviceidHumidityOffsetResponse = vDeviceResponse;

/**
 * Temperature offset parameters.
 */
export const vPost1DevicesByDeviceidTemperatureOffsetBody = vTemperatureOffsetParams;

export const vPost1DevicesByDeviceidTemperatureOffsetPath = v.object({
  deviceid: v.string(),
});

/**
 * DeviceResponse
 */
export const vPost1DevicesByDeviceidTemperatureOffsetResponse = vDeviceResponse;

/**
 * EchonetLiteApplianceResponse
 */
export const vGet1EchonetliteAppliancesResponse = vEchonetLiteApplianceResponse;

/**
 * RefreshELPropertyRequest
 */
export const vPost1EchonetliteAppliancesByApplianceidRefreshBody = vRefreshElPropertyRequest;

export const vPost1EchonetliteAppliancesByApplianceidRefreshPath = v.object({
  applianceid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1EchonetliteAppliancesByApplianceidRefreshResponse = vEmptyObject;

/**
 * SetELPropertyRequest
 */
export const vPost1EchonetliteAppliancesByApplianceidSetBody = vSetElPropertyRequest;

export const vPost1EchonetliteAppliancesByApplianceidSetPath = v.object({
  applianceid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1EchonetliteAppliancesByApplianceidSetResponse = vEmptyObject;

/**
 * UpdateEVCCStateRequest
 */
export const vPost1EvccAppliancesByApplianceidStateBody = vUpdateEvccStateRequest;

export const vPost1EvccAppliancesByApplianceidStatePath = v.object({
  applianceid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1EvccAppliancesByApplianceidStateResponse = vEmptyObject;

/**
 * HomeResponses
 */
export const vGet1HomesResponse = vHomeResponses;

/**
 * HomeParams
 */
export const vPost1HomesBody = vHomeParams;

/**
 * HomeResponse
 */
export const vPost1HomesResponse = vHomeResponse;

/**
 * HomeParams
 */
export const vPost1HomesByHomeidBody = vHomeParams;

export const vPost1HomesByHomeidPath = v.object({
  homeid: v.string(),
});

/**
 * HomeResponse
 */
export const vPost1HomesByHomeidResponse = vHomeResponse;

export const vPost1HomesByHomeidDeletePath = v.object({
  homeid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1HomesByHomeidDeleteResponse = vEmptyObject;

export const vGet1HomesByHomeidDevicesPath = v.object({
  homeid: v.string(),
});

/**
 * DeviceResponses
 */
export const vGet1HomesByHomeidDevicesResponse = vDeviceResponses;

export const vPost1HomesByHomeidInvitesPath = v.object({
  homeid: v.string(),
});

/**
 * HomeInvite
 */
export const vPost1HomesByHomeidInvitesResponse = vHomeInvite;

/**
 * HomeUserParams
 */
export const vPost1HomesByHomeidKickBody = vHomeUserParams;

export const vPost1HomesByHomeidKickPath = v.object({
  homeid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1HomesByHomeidKickResponse = vEmptyObject;

export const vPost1HomesByHomeidLocationPath = v.object({
  homeid: v.string(),
});

/**
 * HomeResponse
 */
export const vPost1HomesByHomeidLocationResponse = vHomeResponse;

/**
 * DeleteLocationRequest
 */
export const vPost1HomesByHomeidLocationDeleteBody = vHomesDeleteLocationRequest;

export const vPost1HomesByHomeidLocationDeletePath = v.object({
  homeid: v.string(),
});

/**
 * DeleteLocationResponse
 */
export const vPost1HomesByHomeidLocationDeleteResponse = vHomesDeleteLocationResponse;

export const vPost1HomesByHomeidLocationStateUpdatePath = v.object({
  homeid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1HomesByHomeidLocationStateUpdateResponse = vEmptyObject;

/**
 * HomeUserParams
 */
export const vPost1HomesByHomeidOwnerBody = vHomeUserParams;

export const vPost1HomesByHomeidOwnerPath = v.object({
  homeid: v.string(),
});

/**
 * HomeResponse
 */
export const vPost1HomesByHomeidOwnerResponse = vHomeResponse;

export const vPost1HomesByHomeidPartPath = v.object({
  homeid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1HomesByHomeidPartResponse = vEmptyObject;

/**
 * TransferRequest
 */
export const vPost1HomesByHomeidTransferByTohomeidBody = vTransferRequest;

export const vPost1HomesByHomeidTransferByTohomeidPath = v.object({
  homeid: v.string(),
  tohomeid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1HomesByHomeidTransferByTohomeidResponse = vEmptyObject;

export const vGet1HomesByHomeidUsersPath = v.object({
  homeid: v.string(),
});

/**
 * UserAndRoles
 */
export const vGet1HomesByHomeidUsersResponse = vUserAndRoles;

export const vGet1InvitesByInvitetokenPath = v.object({
  invitetoken: v.string(),
});

/**
 * HomeInvite
 */
export const vGet1InvitesByInvitetokenResponse = vHomeInvite;

export const vPost1InvitesByInvitetokenPath = v.object({
  invitetoken: v.string(),
});

/**
 * HomeResponse
 */
export const vPost1InvitesByInvitetokenResponse = vHomeResponse;

/**
 * Signal parameters.
 */
export const vPost1SignalsBySignalidBody = vUpdateSignalParameters;

export const vPost1SignalsBySignalidPath = v.object({
  signalid: v.string(),
});

/**
 * Signal
 */
export const vPost1SignalsBySignalidResponse = vSignal;

/**
 * EmptyObject
 */
export const vPost1SignalsBySignalidDeleteBody = vEmptyObject;

export const vPost1SignalsBySignalidDeletePath = v.object({
  signalid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1SignalsBySignalidDeleteResponse = vEmptyObject;

/**
 * EmptyObject
 */
export const vPost1SignalsBySignalidSendBody = vEmptyObject;

export const vPost1SignalsBySignalidSendPath = v.object({
  signalid: v.string(),
});

/**
 * EmptyObject
 */
export const vPost1SignalsBySignalidSendResponse = vEmptyObject;

/**
 * User information.
 */
export const vGet1UsersMeResponse = vUserResponse;

/**
 * UpdateProfileParam
 */
export const vPost1UsersMeBody = vUpdateProfileParam;

/**
 * User information.
 */
export const vPost1UsersMeResponse = vUserResponse;

/**
 * AirConParams_
 */
export const vPost2AppliancesByApplianceidAirconSettingsBody = vAirConParams;

export const vPost2AppliancesByApplianceidAirconSettingsPath = v.object({
  applianceid: v.string(),
});

/**
 * ApplianceResponse
 */
export const vPost2AppliancesByApplianceidAirconSettingsResponse = vApplianceResponse;

/**
 * DetectApplianceV2Request
 */
export const vPost2DetectapplianceBody = vAppliancesDetectApplianceV2Request;

/**
 * DetectApplianceV2Response
 */
export const vPost2DetectapplianceResponse = vAppliancesDetectApplianceV2Response;
